(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function ba(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var ca=ba(this),da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={M:!0},ia={};try{ia.__proto__=ha;fa=ia.M;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype}function l(a,b){if(b){var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
function la(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}l("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=la(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});
l("Object.setPrototypeOf",function(a){return a||ja});var ma=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=da(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
l("Reflect.construct",function(){return ma});l("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==la(this,b,"includes").indexOf(b,c||0)}});var m=this||self;function na(){}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){var b=n(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function r(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.$=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},t=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function ta(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ua(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function wa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<va.length;f++)c=va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function u(a,b){this.a=a===xa&&b||"";this.b=ya}g=u.prototype;g.s=!0;g.m=function(){return this.a.toString()};g.C=!0;g.i=function(){return 1};g.aa=function(a,b){var c=za(this).toString();c=Aa.exec(c);var d=c[3]||"";return new u(xa,c[1]+Ba("?",c[2]||"",a)+Ba("#",d,b))};function za(a){return a instanceof u&&a.constructor===u&&a.b===ya?a.a:"type_error:TrustedResourceUrl"}var Aa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ya={};
function Ba(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b}var xa={};var Ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Da(a,b){if(b)a=a.replace(Ea,"&amp;").replace(Fa,"&lt;").replace(Ga,"&gt;").replace(Ha,"&quot;").replace(Ia,"&#39;").replace(Ja,"&#0;");else{if(!Ka.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ea,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Fa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ga,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ha,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ia,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ja,"&#0;"))}return a}
var Ea=/&/g,Fa=/</g,Ga=/>/g,Ha=/"/g,Ia=/'/g,Ja=/\x00/g,Ka=/[\x00&<>"']/;function La(a,b){return a<b?-1:a>b?1:0};function v(a,b){this.a=a===Ma&&b||"";this.b=Na}v.prototype.s=!0;v.prototype.m=function(){return this.a.toString()};v.prototype.C=!0;v.prototype.i=function(){return 1};var Na={},Ma={};var w;a:{var Oa=m.navigator;if(Oa){var Pa=Oa.userAgent;if(Pa){w=Pa;break a}}w=""};function x(){this.a="";this.c=Qa;this.b=null}x.prototype.C=!0;x.prototype.i=function(){return this.b};x.prototype.s=!0;x.prototype.m=function(){return this.a.toString()};function y(a){return a instanceof x&&a.constructor===x&&a.c===Qa?a.a:"type_error:SafeHtml"}function z(a){if(a instanceof x)return a;var b="object"==typeof a,c=null;b&&a.C&&(c=a.i());return Ra(Da(b&&a.s?a.m():String(a)),c)}
function Sa(a){function b(f){Array.isArray(f)?t(f,b):(f=z(f),e.push(y(f).toString()),f=f.i(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=z(Ta),d=c.i(),e=[];t(a,b);return Ra(e.join(y(c).toString()),d)}function Ua(a){return Sa(Array.prototype.slice.call(arguments))}var Qa={};function Ra(a,b){return A(a,b)}function A(a,b){var c=new x;c.a=a;c.b=b;return c}A("<!DOCTYPE html>",0);var Ta=A("",0),Va=A("<br>",0);var Wa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=y(Ta);return!b.parentElement});function Xa(a,b){if(Wa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=y(b)};function B(a){return a=Da(a,void 0)};var C="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""};function D(){}D.prototype.a=function(){throw C;};D.prototype.j=function(){return this};function Ya(a){if(a instanceof D)return a;if("function"==typeof a.j)return a.j(!1);if(p(a)){var b=0,c=new D;c.a=function(){for(;;){if(b>=a.length)throw C;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Za(a,b){if(p(a))try{t(a,b,void 0)}catch(c){if(c!==C)throw c;}else{a=Ya(a);try{for(;;)b.call(void 0,a.a(),void 0,a)}catch(c){if(c!==C)throw c;}}}function $a(a){if(p(a))return sa(a);a=Ya(a);var b=[];Za(a,function(c){b.push(c)});return b};var E={},ab={},bb={};function F(){throw Error("Do not instantiate directly");}F.prototype.w=null;F.prototype.toString=function(){return this.G};F.prototype.a=function(){if(this.f!==ab)throw Error("Sanitized content was not of kind URI.");return new v(Ma,this.toString())};function cb(){F.call(this)}r(cb,F);cb.prototype.f=E;function db(a){db[" "](a);return a}db[" "]=na;function eb(a,b){var c=fb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var gb=-1!=w.indexOf("Opera"),G=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),hb=-1!=w.indexOf("Edge"),H=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),I=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),ib=-1!=w.indexOf("Macintosh");function jb(){var a=m.document;return a?a.documentMode:void 0}var kb;
a:{var lb="",mb=function(){var a=w;if(H)return/rv:([^\);]+)(\)|;)/.exec(a);if(hb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(I)return/WebKit\/(\S+)/.exec(a);if(gb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();mb&&(lb=mb?mb[1]:"");if(G){var nb=jb();if(null!=nb&&nb>parseFloat(lb)){kb=String(nb);break a}}kb=lb}var ob=kb,fb={};
function K(a){return eb(a,function(){for(var b=0,c=Ca(String(ob)).split("."),d=Ca(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=La(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||La(0==h[2].length,0==k[2].length)||La(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var pb;
if(m.document&&G){var qb=jb();pb=qb?qb:parseInt(ob,10)||void 0}else pb=void 0;var L=pb;function rb(a){if(null!=a)switch(a.w){case 1:return 1;case -1:return-1;case 0:return 0}return null}function sb(a){return null!=a&&a.f===E?a:a instanceof x?M(y(a).toString(),a.i()):M(B(String(String(a))),rb(a))}var M=function(a){function b(c){this.G=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.w=d);return c}}(cb);function tb(a){return null!=a&&a.f===E?String(String(a.G).replace(ub,"").replace(vb,"&lt;")).replace(wb,xb):B(String(a))}
function yb(a){null!=a&&a.f===ab||null!=a&&a.f===bb?a=String(a).replace(zb,Ab):a instanceof v?(a=a instanceof v&&a.constructor===v&&a.b===Na?a.a:"type_error:SafeUrl",a=String(a).replace(zb,Ab)):a instanceof u?a=String(za(a).toString()).replace(zb,Ab):(a=String(a),a=Bb.test(a)?a.replace(zb,Ab):"about:invalid#zSoyz");return a}
var Cb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function xb(a){return Cb[a]}
var Db={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function Ab(a){return Db[a]}var wb=/[\x00\x22\x27\x3c\x3e]/g,zb=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Bb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,ub=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,vb=/</g;function Eb(){return M('<div class="devsite-snackbar-snack" type="loading"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Loading</div><div class="devsite-snackbar-action"><devsite-spinner single-color="#ffffff"></devsite-spinner></div></div></div>')}
function Fb(){return M('<div class="devsite-snackbar-snack" type="refresh"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">A new version is available</div><button class="devsite-snackbar-action">Refresh</button></div></div>')}
function Gb(){return M('<div class="devsite-snackbar-snack" type="error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Something went wrong. Please try again.</div><button class="devsite-snackbar-action">Retry</button></div></div>')}function Hb(){return M('<div class="devsite-snackbar-snack" type="copied-to-clipboard"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Copied to clipboard</div></div></div>')}
function Ib(a){a=a||{};a=a.D;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">This site uses cookies from Google to deliver its services and to analyze traffic.</div><a href="'+((a?tb(yb(a)):"//policies.google.com/technologies/cookies")+'" class="devsite-snackbar-link button">');return M(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')}
function Jb(){return M('<div class="devsite-snackbar-snack" type="support-attachment-error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Unsupported file type.</div><button class="devsite-snackbar-action">OK</button></div></div>')}
function Kb(a){var b=a.message,c=a.link,d=a.U;a='<div class="devsite-snackbar-snack" type="'+tb(a.W)+'"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+sb(b)+'</div><button class="devsite-snackbar-action">';a=a+'No, thanks</button><a href="'+(tb(yb(c))+'" class="devsite-snackbar-link button" target="_blank">');a=d?a+sb(d):a+"OK";return M(a+"</a></div></div>")}
function Lb(a){var b=a.V;a='<div class="devsite-snackbar-snack" type="custom"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+sb(a.message)+"</div>";b&&(a+='<button class="devsite-snackbar-action">OK</button>');return M(a+"</div></div>")};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Mb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Mb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function N(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ka(N,HTMLElement);N.prototype.L=function(){console.warn(this.tagName,"has not implemented update")};N.prototype.H=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
N.prototype.K=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var Nb=!G||9<=Number(L),Ob=!H&&!G||G&&9<=Number(L)||H&&K("1.9.1"),Pb=G&&!K("9"),Qb=G||gb||I;function O(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=O.prototype;g.gb=function(){return new O(this.a,this.b)};g.da=function(a){return a instanceof O&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.ib=function(a,b){a instanceof O?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.hb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.Eb=function(a,b){a=a*Math.PI/180;b=b||new O(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Rb(a,b){this.width=a;this.height=b}g=Rb.prototype;g.jb=function(){return new Rb(this.width,this.height)};g.Da=function(){return Math.max(this.width,this.height)};g.Qa=function(){return Math.min(this.width,this.height)};g.Ab=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.qb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ha=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Sb(a,b){a.width*=b;a.height*=b;return a}g.Gb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Sb(this,a)};
g.Hb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Sb(this,a)};function Tb(a){return a?new P(Q(a)):pa||(pa=new P)}function Ub(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Vb(document,"*",a,b);return d||null}
function Wb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=qa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Vb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Wb(a,b,c,d)[0]||null}function Xb(a,b){ta(b,function(c,d){c&&"object"==typeof c&&c.s&&(c=c.m());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Yb.hasOwnProperty(d)?a.setAttribute(Yb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Yb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Zb(a){a=a.document;a=$b(a)?a.documentElement:a.body;return new Rb(a.clientWidth,a.clientHeight)}function ac(a){return a.scrollingElement?a.scrollingElement:!I&&$b(a)?a.documentElement:a.body||a.documentElement}
function bc(a){return a.parentWindow||a.defaultView}function cc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];p(f)&&!dc(f)?t(fc(f)?sa(f):f,e):e(f)}}function R(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function $b(a){return"CSS1Compat"==a.compatMode}function gc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function hc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function ic(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function dc(a){return q(a)&&0<a.nodeType}function jc(a){return q(a)&&1==a.nodeType}function kc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function lc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return mc(b,a)}function mc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function nc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else gc(a),a.appendChild(Q(a).createTextNode(String(b)))}function oc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||oc(a,b,c,d))return!0;a=a.nextSibling}return!1}var pc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},qc={IMG:" ",BR:"\n"};
function rc(a){return sc(a)&&tc(a)}function sc(a){return G&&!K("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function tc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function uc(a){if(Pb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];vc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Pb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function vc(a,b,c){if(!(a.nodeName in pc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in qc)b.push(qc[a.nodeName]);else for(a=a.firstChild;a;)vc(a,b,c),a=a.nextSibling}function fc(a){if(a&&"number"==typeof a.length){if(q(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==n(a))return"function"==typeof a.item}return!1}
function wc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return xc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=qa(f.className.split(/\s+/),c));return h},!0,d)}function xc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||m.document||document}g=P.prototype;g.ua=Tb;g.Ib=function(a){this.a=a};g.qa=function(){return this.a};
g.P=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Oa=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.X=P.prototype.P;g.Xa=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.R=function(a,b,c){return Wb(this.a,a,b,c)};g.wa=function(a,b,c){return Vb(this.a,a,b,c)};g.xa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Wb(document,"*",a,b)};g.va=function(a,b){return Ub(a,b||this.a)};
g.Pa=function(a,b){return Ub(a,b||this.a)};g.Y=P.prototype.R;g.Kb=Xb;g.Sa=function(a){return Zb(a||bc(this.a)||window)};g.ra=function(){var a=bc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Zb(a).height,$b(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.N=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Nb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',B(h.name),'"');if(h.type){f.push(' type="',B(h.type),'"');var k={};wa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=R(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):Xb(f,h));2<e.length&&cc(d,f,e,2);return f};g.Z=P.prototype.N;g.Wa=function(a){return this.a.createTextNode(String(a))};
g.ca=function(a,b,c){var d=this.a;c=!!c;for(var e=R(d,"TABLE"),f=e.appendChild(R(d,"TBODY")),h=0;h<a;h++){for(var k=R(d,"TR"),J=0;J<b;J++){var ec=R(d,"TD");c&&nc(ec,"\u00a0");k.appendChild(ec)}f.appendChild(k)}return e};g.Fb=function(a){var b=this.a;var c=R(b,"DIV");G?(a=Ua(Va,a),Xa(c,a),c.removeChild(c.firstChild)):Xa(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.ob=function(){return $b(this.a)};
g.ta=function(){return ac(this.a)};g.sa=function(){var a=this.a,b=ac(a);a=bc(a);return G&&K("10")&&a.pageYOffset!=b.scrollTop?new O(b.scrollLeft,b.scrollTop):new O(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ja=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Ua=function(a,b){a.appendChild(b)};g.Ta=function(a,b){cc(Q(a),a,arguments,1)};g.Va=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Db=gc;g.mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.kb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Ya=hc;g.Za=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ia=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return hc(a)}};
g.oa=function(a){return Ob&&void 0!=a.children?a.children:ra(a.childNodes,function(b){return 1==b.nodeType})};g.ya=function(a){return void 0!==a.firstElementChild?a.firstElementChild:ic(a.firstChild,!0)};g.Ba=function(a){return void 0!==a.lastElementChild?a.lastElementChild:ic(a.lastChild,!1)};g.Ea=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:ic(a.nextSibling,!0)};g.Ma=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:ic(a.previousSibling,!1)};
g.Fa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Na=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.tb=dc;g.pb=jc;g.vb=function(a){return q(a)&&a.window==a};g.La=function(a){var b;if(Qb&&!(G&&K("9")&&!K("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return jc(b)?b:null};
g.contains=kc;
g.ba=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(G&&!(9<=Number(L))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?mc(a,b):!c&&kc(e,b)?-1*lc(a,b):!d&&kc(f,a)?lc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.ea=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ka=Q;g.za=function(a){return a.contentDocument||a.contentWindow.document};
g.Aa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?bc(c):window}else d=null;b=d}return b}catch(e){}return null};g.Lb=nc;g.Ja=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.fa=function(a,b){var c=[];return oc(a,b,c,!0)?c[0]:void 0};g.ga=function(a,b){var c=[];oc(a,b,c,!1);return c};g.sb=rc;g.Jb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.rb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!sc(a)||tc(a)):rc(a))&&G){var c;"function"!=n(a.getBoundingClientRect)||G&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ra=uc;g.Ha=function(a){return uc(a).length};
g.Ia=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(uc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ga=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in pc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in qc)d+=qc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);q(c)&&(c.Cb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.ub=fc;g.ma=wc;g.la=function(a,b,c){return wc(a,null,b,c)};g.ka=xc;g.na=function(a){return a.getContext("2d")};function yc(){this.g=this.g;this.b=this.b}g=yc.prototype;g.g=!1;g.T=function(){return this.g};g.pa=yc.prototype.T;g.F=function(){this.g||(this.g=!0,this.A())};g.Bb=function(a){a=oa(zc,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.A=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function zc(a){a&&"function"==typeof a.F&&a.F()};var Ac=!G||9<=Number(L),Bc=!G||9<=Number(L),Cc=G&&!K("9"),Dc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",na,b),m.removeEventListener("test",na,b)}catch(c){}return a}();function Ec(a,b){this.type=a;this.b=this.target=b;this.K=this.h=!1}Ec.prototype.stopPropagation=function(){this.h=!0};Ec.prototype.c=function(){this.K=!0};var Fc;Fc=I?"webkitTransitionEnd":gb?"otransitionend":"transitionend";function S(a,b){Ec.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.I=this.H=0;this.key="";this.o=this.B=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.J=null;this.L=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(H){a:{try{db(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.H=I||void 0!==a.offsetX?a.offsetX:a.layerX,this.I=I||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.B=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.L=ib?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Gc[a.pointerType]||"";this.J=a.state;this.a=a;a.defaultPrevented&&this.c()}}r(S,Ec);var Hc=[1,4,2],Gc={2:"touch",3:"pen",4:"mouse"};
S.prototype.Mb=function(){return(Ac?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Hc[0]))&&!(I&&ib&&this.ctrlKey)};S.prototype.stopPropagation=function(){S.u.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.c=function(){S.u.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ic="closure_listenable_"+(1E6*Math.random()|0),Jc=0;function Kc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Jc;this.l=this.v=!1}function Lc(a){a.l=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Mc(a){this.src=a;this.a={};this.b=0}g=Mc.prototype;g.bb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Nc(a,b,d,e);-1<h?(b=a[h],c||(b.v=!1)):(b=new Kc(b,this.src,f,!!d,e),b.v=c,a.push(b));return b};
g.eb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Nc(e,b,c,d);return-1<b?(Lc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.fb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Lc(d[e]);delete this.a[c];this.b--}return b};g.Ca=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.cb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ua(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function Nc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.l&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Oc="closure_lm_"+(1E6*Math.random()|0),Pc={},Qc=0;function Rc(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Rc(a,b[f],c,d,e);return null}c=Sc(c);return a&&a[Ic]?U(a,b,c,q(d)?!!d.capture:!!d,e):Tc(a,b,c,!1,d,e)}
function Tc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=q(e)?!!e.capture:!!e,k=Uc(a);k||(a[Oc]=k=new Mc(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Vc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Dc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Wc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Qc++;return c}
function Vc(){var a=Xc,b=Bc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function T(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)T(a,b[f],c,d,e);return null}c=Sc(c);return a&&a[Ic]?a.J(b,c,q(d)?!!d.capture:!!d,e):Tc(a,b,c,!0,d,e)}
function Yc(a){if("number"!==typeof a&&a&&!a.l){var b=a.src;if(b&&b[Ic])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Wc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Qc--;if(c=Uc(b)){d=a.type;if(d in c.a){var e=c.a[d],f=qa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(Lc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Oc]=null)}else Lc(a)}}}
function Wc(a){return a in Pc?Pc[a]:Pc[a]="on"+a}function Zc(a,b,c,d){var e=!0;if(a=Uc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.l&&(f=$c(f,d),e=e&&!1!==f)}return e}function $c(a,b){var c=a.listener,d=a.b||a.src;a.v&&Yc(a);return c.call(d,b)}
function Xc(a,b){if(a.l)return!0;if(!Bc){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new S(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.h&&0<=e;e--){b.b=d[e];var f=Zc(d[e],a,!0,b);c=c&&f}for(e=0;!b.h&&e<d.length;e++)b.b=d[e],f=Zc(d[e],a,!1,b),c=
c&&f}return c}return $c(a,new S(b,this))}function Uc(a){a=a[Oc];return a instanceof Mc?a:null}var ad="__closure_events_fn_"+(1E9*Math.random()>>>0);function Sc(a){if("function"==n(a))return a;a[ad]||(a[ad]=function(b){return a.handleEvent(b)});return a[ad]};function V(a){yc.call(this);this.c=a;this.a={}}r(V,yc);var bd=[];function cd(a,b,c){U(a,b,"click",c,void 0)}g=V.prototype;g.xb=function(a,b,c,d,e){return U(this,a,b,c,d,e)};function U(a,b,c,d,e,f){Array.isArray(c)||(c&&(bd[0]=c.toString()),c=bd);for(var h=0;h<c.length;h++){var k=Rc(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.ab=function(a,b,c,d){return dd(this,a,b,c,d)};g.wb=function(a,b,c,d,e){return dd(this,a,b,c,d,e)};
function dd(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)dd(a,b,c[h],d,e,f);else{b=T(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.yb=function(a,b,c,d){U(b,a,c,d,this.c||this);return this};g.zb=function(a,b,c,d,e){U(b,a,c,d,e||this.c||this);return this};g.$a=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function ed(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)ed(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=q(e)?!!e.capture:!!e,f=f||a.c||a,d=Sc(d),e=!!e,b&&b[Ic]?c=b.I(c,d,e,f):b?(b=Uc(b))?(c=b.a[c.toString()],b=-1,c&&(b=Nc(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Yc(c),delete a.a[c.key])}g.Nb=function(a,b,c,d,e){ed(b,a,c,d,e||this.c||this,this);return this};function fd(a){ta(a.a,function(b,c){this.a.hasOwnProperty(c)&&Yc(b)},a);a.a={}}g.A=function(){V.u.A.call(this);fd(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function W(a,b){b=a(b||gd,void 0,void 0);a=Tb();a=R(a.a,"DIV");if(q(b))if(b instanceof F){if(b.f!==E)throw Error("Sanitized content was not of kind HTML.");b=A(b.toString(),b.w||null)}else b=z("zSoyz");else b=z(String(b));Xa(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var gd={};function hd(){};function id(){}r(id,hd);id.prototype.O=function(){var a=0;Za(this.j(!0),function(){a++});return a};id.prototype.S=function(){var a=$a(this.j(!0)),b=this;t(a,function(c){b.a.removeItem(c)})};function jd(a){this.a=a}r(jd,id);g=jd.prototype;g.nb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.O=function(){return this.a.length};
g.j=function(a){var b=0,c=this.a,d=new D;d.a=function(){if(b>=c.length)throw C;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};g.S=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function kd(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}r(kd,jd);var ld={},md=(ld[0]=Ib,ld[1]=Ib,ld[2]=function(a){a=a||{};a=a.D;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Google uses cookies to deliver its services, to personalize ads, and to analyze traffic. You can adjust your privacy controls anytime in your <a href="//myaccount.google.com/intro/data-and-personalization">Google settings</a>.</div><a href="'+((a?tb(yb(a)):"//policies.google.com/technologies/cookies")+
'" class="devsite-snackbar-link button">');return M(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')},ld);function X(){var a=N.call(this)||this;a.h=-1;a.o=new V(a);a.b=new kd;a.a=[];return a}ka(X,N);X.prototype.connectedCallback=function(){U(this.o,document.body,"devsite-show-custom-snackbar-msg",this.B,void 0)};X.prototype.disconnectedCallback=function(){fd(this.o)};
X.prototype.B=function(a){var b=this;this.setAttribute("type","custom");if(a=a.a.detail){var c=!!a.showClose,d=W(Lb,{message:a.msg,V:c});c&&T(d.querySelector(".devsite-snackbar-action"),"click",function(){Y(b,d)});Z(this,d,!c)}};
X.prototype.attributeChangedCallback=function(a,b,c){if("type"==a){switch(b){case "loading":Y(this,this.querySelector('*[type^="loading"]'));break;case "refresh":Y(this,this.querySelector('*[type^="refresh"]'));break;case "error":Y(this,this.querySelector('*[type^="error"]'));break;case "copied-to-clipboard":Y(this,this.querySelector('*[type^="copied-to-clipboard"]'));break;case "cookie-notification":nd(this);break;case "support-attachment-error":od(this);break;case "custom":Y(this,this.querySelector('*[type^="custom"]'))}null!=
b&&b.startsWith("notification-")&&pd(this);c&&(c.includes(",")&&(this.a=c.split(","),c=this.a.shift()),qd(this,c))}};function qd(a,b){switch(b){case "loading":if(!a.querySelector('*[type^="loading"]')){var c=W(Eb);Z(a,c)}break;case "refresh":rd(a);break;case "error":sd(a);break;case "copied-to-clipboard":c=W(Hb);Z(a,c,!0);break;case "cookie-notification":td(a);break;case "support-attachment-error":ud(a)}b.startsWith("notification-")&&vd(a,b)}
function Z(a,b,c){c=void 0===c?!1:c;a.appendChild(b);window.requestAnimationFrame(function(){wd(a,b,c)})}function wd(a,b,c){c=void 0===c?!1:c;window.clearTimeout(a.h);a.c?Y(a,a.c,b,c):(a.c=b,window.requestAnimationFrame(function(){b.setAttribute("show","")}),c&&(a.h=window.setTimeout(function(){a.removeAttribute("type");Y(a,b)},5E3)))}function rd(a){var b=W(Fb);Rc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}
function sd(a){var b=W(Gb);Rc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}function Y(a,b,c,d){c=void 0===c?null:c;d=void 0===d?!1:d;b&&(T(b,Fc,function(){hc(b);a.c=null;if(c)wd(a,c,d);else{var e=a.a.length?a.a.shift():null;null!==e&&qd(a,e)}}),b.removeAttribute("show"))}
function td(a){if(a.b.get("devsite-eu-cookie")){var b=a.a.length?a.a.shift():null;null!==b&&qd(a,b)}else{b=Ib;a.hasAttribute("data-cookie-notice")&&(b=parseInt(a.getAttribute("data-cookie-notice"),10),b=md[b]);if(a.hasAttribute("data-cookie-policy")){var c=a.getAttribute("data-cookie-policy");b=W(b,{D:c})}else b=W(b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){a.b.set("devsite-eu-cookie","1");nd(a)});Z(a,b)}}
function nd(a){Y(a,a.querySelector('*[type^="cookie-notification"]'))}function ud(a){var b=W(Jb);Z(a,b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){od(a)})}function od(a){Y(a,a.querySelector('*[type^="support-attachment-error"]'))}
function vd(a,b){var c=a.getAttribute(b+"-message"),d=a.getAttribute(b+"-link"),e=a.getAttribute(b+"-link-txt"),f=a.hasAttribute(b+"-store-key");if(c&&d){var h="devsite-notification"+d;if(!f||!a.b.get(h)){b=W(Kb,{W:b,message:c,link:d,U:e});Z(a,b);var k=new V(b);cd(k,b,function(J){J.stopPropagation();if(J.target.classList.contains("devsite-snackbar-link")||J.target.classList.contains("devsite-snackbar-action"))f&&a.b.set(h,"1"),pd(a),fd(k)})}}}
function pd(a){Y(a,a.querySelector('*[type^="notification"]'))}ca.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["type"]}}});X.prototype.attributeChangedCallback=X.prototype.attributeChangedCallback;X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;try{window.customElements.define("devsite-snackbar",X)}catch(a){console.warn("devsite.app.customElement.DevsiteSnackBar",a)};}).call(this);
