(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ca(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var m=ca(this);function da(){da=function(){};m.Symbol||(m.Symbol=ea)}function fa(a,b){this.a=a;ba(this,"description",{configurable:!0,writable:!0,value:b})}fa.prototype.toString=function(){return this.a};
var ea=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new fa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function ha(){da();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(aa(this))}});ha=function(){}}function ia(a){ha();a={next:a};a[m.Symbol.iterator]=function(){return this};return a}
function ja(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ka="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},la;if("function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={Y:!0},oa={};try{oa.__proto__=na;ma=oa.Y;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var pa=la;function qa(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.K=b.prototype}function ra(a,b){if(b){var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ra("Promise",function(a){function b(g){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{g(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(k){k(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(g)};var e=m.setTimeout;c.prototype.c=function(g){e(g,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var k=0;k<g.length;++k){var l=
g[k];g[k]=null;try{l()}catch(n){this.f(n)}}}this.a=null};c.prototype.f=function(g){this.c(function(){throw g;})};b.prototype.c=function(){function g(n){return function(v){l||(l=!0,n.call(k,v))}}var k=this,l=!1;return{resolve:g(this.I),reject:g(this.f)}};b.prototype.I=function(g){if(g===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.J(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?this.s(g):this.h(g)}};
b.prototype.s=function(g){var k=void 0;try{k=g.then}catch(l){this.f(l);return}"function"==typeof k?this.R(k,g):this.h(g)};b.prototype.f=function(g){this.i(2,g)};b.prototype.h=function(g){this.i(1,g)};b.prototype.i=function(g,k){if(0!=this.b)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.b);this.b=g;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)f.b(this.a[g]);this.a=null}};var f=new c;b.prototype.J=function(g){var k=this.c();
g.D(k.resolve,k.reject)};b.prototype.R=function(g,k){var l=this.c();try{g.call(k,l.resolve,l.reject)}catch(n){l.reject(n)}};b.prototype.then=function(g,k){function l(z,F){return"function"==typeof z?function(Ma){try{n(z(Ma))}catch(Na){v(Na)}}:F}var n,v,Oa=new b(function(z,F){n=z;v=F});this.D(l(g,n),l(k,v));return Oa};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.D=function(g,k){function l(){switch(n.b){case 1:g(n.g);break;case 2:k(n.g);break;default:throw Error("Unexpected state: "+
n.b);}}var n=this;null==this.a?f.b(l):this.a.push(l)};b.resolve=d;b.reject=function(g){return new b(function(k,l){l(g)})};b.race=function(g){return new b(function(k,l){for(var n=ja(g),v=n.next();!v.done;v=n.next())d(v.value).D(k,l)})};b.all=function(g){var k=ja(g),l=k.next();return l.done?d([]):new b(function(n,v){function Oa(Ma){return function(Na){z[Ma]=Na;F--;0==F&&n(z)}}var z=[],F=0;do z.push(void 0),F++,d(l.value).D(Oa(z.length-1),v),l=k.next();while(!l.done)})};return b});
function sa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ta(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.g=this.c=0;this.i=this.b=null}function ua(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}h=ta.prototype;h.L=function(a){this.j=a};function va(a,b){a.b={T:b,X:!0};a.a=a.c||a.g}h.return=function(a){this.b={return:a};this.a=this.g};h.$b=function(a){this.b={B:a};this.a=this.g};
function p(a,b,c){a.a=c;return{value:b}}h.Ac=function(a,b){a=ja(a);var c=a.next();sa(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,p(this,c.value,b)};h.B=function(a){this.a=a};h.qc=function(a){this.c=0;this.g=a||0};function wa(a){a.c=0;var b=a.b.T;a.b=null;return b}h.na=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.c=a||0;this.g=b||0};
h.ac=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.X?this.a=this.c||this.g:void 0!=b.B&&this.g<b.B?(this.a=b.B,this.b=null):this.a=this.g:this.a=a};h.ua=function(a){return new xa(a)};function xa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}xa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ya(a){this.a=new ta;this.b=a}
function za(a,b){ua(a.a);var c=a.a.f;if(c)return Aa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return q(a)}function Aa(a,b,c,d){try{var e=b.call(a.a.f,c);sa(e);if(!e.done)return a.a.h=!1,e;var f=e.value}catch(g){return a.a.f=null,va(a.a,g),q(a)}a.a.f=null;d.call(a.a,f);return q(a)}
function q(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,va(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.X)throw b.T;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function Ba(a){this.next=function(b){ua(a.a);a.a.f?b=Aa(a,a.a.f.next,b,a.a.L):(a.a.L(b),b=q(a));return b};this.throw=function(b){ua(a.a);a.a.f?b=Aa(a,a.a.f["throw"],b,a.a.L):(va(a.a,b),b=q(a));return b};this.return=function(b){return za(a,b)};ha();this[Symbol.iterator]=function(){return this}}function Ca(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function Da(a){return Ca(new Ba(new ya(a)))}ra("Object.setPrototypeOf",function(a){return a||pa});
var Ea=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ka(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();ra("Reflect.construct",function(){return Ea});
ra("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});var r=this||self;
function Fa(a,b){a=a.split(".");var c=r;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Ga(a){if(a&&a!=r)return Ha(a.document);null===Ia&&(Ia=Ha(r.document));return Ia}var Ja=/^[\w+/_-]+[=]{0,2}$/,Ia=null;function Ha(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Ja.test(a)?a:""}
function Ka(a,b){a=a.split(".");b=b||r;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function La(){}
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Pa(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Ra=Date.now||function(){return+new Date};
function Sa(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ja=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var Ta;var w=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ua=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d};function Va(a){return Array.prototype.concat.apply([],arguments)}function Wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Xa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ya(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function $a(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function y(a,b){this.a=a===ab&&b||"";this.b=bb}h=y.prototype;h.H=!0;h.G=function(){return this.a.toString()};h.O=!0;h.A=function(){return 1};h.ka=function(a,b){var c=cb(this).toString();c=db.exec(c);var d=c[3]||"";return new y(ab,c[1]+eb("?",c[2]||"",a)+eb("#",d,b))};function cb(a){if(a instanceof y&&a.constructor===y&&a.b===bb)return a.a;t(a);return"type_error:TrustedResourceUrl"}var db=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,bb={};
function eb(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b}var ab={};var fb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function gb(a,b){if(b)a=a.replace(hb,"&amp;").replace(ib,"&lt;").replace(jb,"&gt;").replace(kb,"&quot;").replace(lb,"&#39;").replace(mb,"&#0;");else{if(!nb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(hb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ib,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(jb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(kb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(lb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(mb,"&#0;"))}return a}
var hb=/&/g,ib=/</g,jb=/>/g,kb=/"/g,lb=/'/g,mb=/\x00/g,nb=/[\x00&<>"']/;function A(a,b){return-1!=a.indexOf(b)}function ob(a,b){return a<b?-1:a>b?1:0};function B(a,b){this.a=a===pb&&b||"";this.b=qb}B.prototype.H=!0;B.prototype.G=function(){return this.a.toString()};B.prototype.O=!0;B.prototype.A=function(){return 1};var qb={},pb={};var C;a:{var rb=r.navigator;if(rb){var sb=rb.userAgent;if(sb){C=sb;break a}}C=""};function D(){this.a="";this.c=tb;this.b=null}D.prototype.O=!0;D.prototype.A=function(){return this.b};D.prototype.H=!0;D.prototype.G=function(){return this.a.toString()};function ub(a){if(a instanceof D&&a.constructor===D&&a.c===tb)return a.a;t(a);return"type_error:SafeHtml"}function vb(a){if(a instanceof D)return a;var b="object"==typeof a,c=null;b&&a.O&&(c=a.A());return wb(gb(b&&a.H?a.G():String(a)),c)}
function xb(a){function b(f){Array.isArray(f)?x(f,b):(f=vb(f),e.push(ub(f).toString()),f=f.A(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=vb(yb),d=c.A(),e=[];x(a,b);return wb(e.join(ub(c).toString()),d)}function zb(a){return xb(Array.prototype.slice.call(arguments))}var tb={};function wb(a,b){return E(a,b)}function E(a,b){var c=new D;c.a=a;c.b=b;return c}E("<!DOCTYPE html>",0);var yb=E("",0),Ab=E("<br>",0);var Bb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=ub(yb);return!b.parentElement});function Cb(a,b){if(Bb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=ub(b)};function Db(a){return a=gb(a,void 0)};var Eb="StopIteration"in r?r.StopIteration:{message:"StopIteration",stack:""};function Fb(){}Fb.prototype.next=function(){throw Eb;};Fb.prototype.a=function(){return this};function Gb(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof Gb)for(c=a.o(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}h=Gb.prototype;h.l=function(){G(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};h.o=function(){G(this);return this.a.concat()};
h.Lb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(H(this.b,c)&&this.b[c]==a)return!0}return!1};h.Mb=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||Hb;G(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Hb(a,b){return a===b}h.Nb=function(){return 0==this.c};h.Kb=function(){this.b={};this.f=this.c=this.a.length=0};
function G(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];H(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],H(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}h.get=function(a,b){return H(this.b,a)?this.b[a]:b};h.set=function(a,b){H(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};h.forEach=function(a,b){for(var c=this.o(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
h.yc=function(){for(var a=new Gb,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};h.xc=function(){G(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};h.Oa=function(){return Ib(this,!0)};h.ib=function(){return Ib(this,!1)};function Ib(a,b){G(a);var c=0,d=a.f,e=new Fb;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw Eb;var f=a.a[c++];return b?f:a.b[f]};return e}
function H(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Jb(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(Pa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Kb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Pa(a)||"string"===typeof a)x(a,b,c);else{if(a.o&&"function"==typeof a.o)var d=a.o();else if(a.l&&"function"==typeof a.l)d=void 0;else if(Pa(a)||"string"===typeof a){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=Jb(a);f=e.length;for(var g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var Lb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Mb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}}
function Nb(a,b,c){for(;0<=(b=a.indexOf("apix",b))&&b<c;){var d=a.charCodeAt(b-1);if(38==d||63==d)if(d=a.charCodeAt(b+4),!d||61==d||38==d||35==d)return b;b+=5}return-1}var Ob=/#|$/;function Pb(){var a=window.location.href,b=a.search(Ob),c=Nb(a,0,b);if(0>c)return null;var d=a.indexOf("&",c);if(0>d||d>b)d=b;c+=5;return decodeURIComponent(a.substr(c,d-c).replace(/\+/g," "))}var Qb=/[?&]($|#)/;
function Rb(){for(var a=window.location.href,b=a.search(Ob),c=0,d,e=[];0<=(d=Nb(a,c,b));)e.push(a.substring(c,d)),c=Math.min(a.indexOf("&",d)+1||b,b);e.push(a.substr(c));return e.join("").replace(Qb,"$1")};function I(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.s=!1;if(a instanceof I){this.g=void 0!==b?b:a.g;Sb(this,a.h);var c=a.j;J(this);this.j=c;c=a.b;J(this);this.b=c;Tb(this,a.f);c=a.c;J(this);this.c=c;Ub(this,Vb(a.a));a=a.i;J(this);this.i=a}else a&&(c=String(a).match(Lb))?(this.g=!!b,Sb(this,c[1]||"",!0),a=c[2]||"",J(this),this.j=K(a),a=c[3]||"",J(this),this.b=K(a,!0),Tb(this,c[4]),a=c[5]||"",J(this),this.c=K(a,!0),Ub(this,c[6]||"",!0),a=c[7]||"",J(this),this.i=K(a)):(this.g=
!!b,this.a=new Wb(null,this.g))}h=I.prototype;h.toString=function(){var a=[],b=this.h;b&&a.push(Xb(b,Yb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Xb(b,Yb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Xb(c,"/"==c.charAt(0)?Zb:$b,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",Xb(c,ac));return a.join("")};
h.resolve=function(a){var b=new I(this),c=!!a.h;c?Sb(b,a.h):c=!!a.j;if(c){var d=a.j;J(b);b.j=d}else c=!!a.b;c?(d=a.b,J(b),b.b=d):c=null!=a.f;d=a.c;if(c)Tb(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(A(e,"./")||A(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(J(b),b.c=d):c=""!==a.a.toString();c?Ub(b,Vb(a.a)):c=!!a.i;c&&(a=a.i,J(b),b.i=a);return b};function Sb(a,b,c){J(a);a.h=c?K(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function Tb(a,b){J(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Ub(a,b,c){J(a);b instanceof Wb?(a.a=b,bc(a.a,a.g)):(c||(b=Xb(b,cc)),a.a=new Wb(b,a.g));return a}h.uc=function(a,b){return Ub(this,a,b)};
h.Ba=function(){return K(this.a.toString())};h.pb=function(){return this.a.toString()};h.sc=function(a,b){J(this);Array.isArray(b)||(b=[String(b)]);dc(this.a,a,b);return this};h.$a=function(a){return this.a.l(a)};h.Za=function(a){return this.a.get(a)};h.Ob=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
h.fc=function(){J(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Ra()).toString(36);J(this);this.a.set("zx",a);return this};h.qb=function(a){J(this);ec(this.a,a);return this};h.vc=function(a){this.s=a;return this};h.Yb=function(){return this.s};function J(a){if(a.s)throw Error("Tried to modify a read-only Uri");}h.rb=function(a){this.g=a;this.a&&bc(this.a,a);return this};
function K(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Xb(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,fc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function fc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Yb=/[#\/\?@]/g,$b=/[#\?:]/g,Zb=/[#\?]/g,cc=/[#\?@]/g,ac=/#/g;function Wb(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function L(a){a.a||(a.a=new Gb,a.b=0,a.c&&Mb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=Wb.prototype;h.nb=function(){L(this);return this.b};h.add=function(a,b){L(this);this.c=null;a=M(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function ec(a,b){L(a);b=M(a,b);H(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,H(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&G(a)))}h.kb=function(){this.a=this.c=null;this.b=0};
h.ob=function(){L(this);return 0==this.b};function gc(a,b){L(a);b=M(a,b);return H(a.a.b,b)}h.lb=function(a){var b=this.l();return 0<=w(b,a)};h.forEach=function(a,b){L(this);this.a.forEach(function(c,d){x(c,function(e){a.call(b,e,d,this)},this)},this)};h.o=function(){L(this);for(var a=this.a.l(),b=this.a.o(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
h.l=function(a){L(this);var b=[];if("string"===typeof a)gc(this,a)&&(b=Va(b,this.a.get(M(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Va(b,a[c])}return b};h.set=function(a,b){L(this);this.c=null;a=M(this,a);gc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};h.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function dc(a,b,c){ec(a,b);0<c.length&&(a.c=null,a.a.set(M(a,b),Wa(c)),a.b+=c.length)}
h.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.o(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};h.oa=function(a){L(this);this.a.forEach(function(b,c){0<=w(a,c)||ec(this,c)},this);return this};function Vb(a){var b=new Wb;b.c=a.c;a.a&&(b.a=new Gb(a.a),b.b=a.b);return b}
function M(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function bc(a,b){b&&!a.f&&(L(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(ec(this,d),dc(this,e,c))},a));a.f=b}h.mb=function(a){for(var b=0;b<arguments.length;b++)Kb(arguments[b],function(c,d){this.add(d,c)},this)};var hc={},ic={},jc={};function N(){throw Error("Do not instantiate directly");}N.prototype.S=null;N.prototype.toString=function(){return this.U};N.prototype.a=function(){if(this.w!==ic)throw Error("Sanitized content was not of kind URI.");return new B(pb,this.toString())};function kc(){N.call(this)}Sa(kc,N);kc.prototype.w=hc;function lc(a){lc[" "](a);return a}lc[" "]=La;function mc(a,b){var c=nc;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var oc=A(C,"Opera"),O=A(C,"Trident")||A(C,"MSIE"),pc=A(C,"Edge"),qc=A(C,"Gecko")&&!(A(C.toLowerCase(),"webkit")&&!A(C,"Edge"))&&!(A(C,"Trident")||A(C,"MSIE"))&&!A(C,"Edge"),P=A(C.toLowerCase(),"webkit")&&!A(C,"Edge"),rc=A(C,"Macintosh");function sc(){var a=r.document;return a?a.documentMode:void 0}var tc;
a:{var uc="",vc=function(){var a=C;if(qc)return/rv:([^\);]+)(\)|;)/.exec(a);if(pc)return/Edge\/([\d\.]+)/.exec(a);if(O)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(P)return/WebKit\/(\S+)/.exec(a);if(oc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();vc&&(uc=vc?vc[1]:"");if(O){var wc=sc();if(null!=wc&&wc>parseFloat(uc)){tc=String(wc);break a}}tc=uc}var xc=tc,nc={};
function Q(a){return mc(a,function(){for(var b=0,c=fb(String(xc)).split("."),d=fb(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=ob(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||ob(0==g[2].length,0==k[2].length)||ob(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})}var yc;
if(r.document&&O){var zc=sc();yc=zc?zc:parseInt(xc,10)||void 0}else yc=void 0;var Ac=yc;var Bc=function(a){function b(c){this.U=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.S=d);return c}}(kc);function Cc(a){return null!=a&&a.w===hc?String(String(a.U).replace(Dc,"").replace(Ec,"&lt;")).replace(Fc,Gc):Db(String(a))}
var Hc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Gc(a){return Hc[a]}
var Ic={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function Jc(a){return Ic[a]}var Fc=/[\x00\x22\x27\x3c\x3e]/g,Kc=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Lc=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,Dc=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Ec=/</g;function Mc(a){var b=a.method,c=a.fa;a=a.$;null!=a&&a.w===ic||null!=a&&a.w===jc?a=String(a).replace(Kc,Jc):a instanceof B?(a instanceof B&&a.constructor===B&&a.b===qb?a=a.a:(t(a),a="type_error:SafeUrl"),a=String(a).replace(Kc,Jc)):a instanceof y?a=String(cb(a).toString()).replace(Kc,Jc):(a=String(a),a=Lc.test(a)?a.replace(Kc,Jc):"about:invalid#zSoyz");return Bc((c?'<div class="devsite-apix">':"")+'<div class="apis-explorer" data-discovery-rest-url="'+Cc(a)+'" data-method-id="'+Cc(b)+'"></div>'+(c?
"</div>":""))}function Nc(){return Bc('<span class="devsite-apix-controls"><button type="button" class="devsite-fullscreen-apix button-flat material-icons"></button><button type="button" class="devsite-dock-apix button-flat material-icons"></button><button type="button" class="devsite-hide-apix button-flat material-icons"></button></span>')}function Oc(){return Bc('<a id="try-it"></a>')}
function Pc(a){var b=a.version,c=a.da;return Bc('<devsite-apix-snippets data-service-name="'+Cc(a.ea)+'" data-service-version="'+Cc(b)+'" data-method-id="'+Cc(c)+'"></devsite-apix-snippets>')}function Qc(){return Bc('<div class="devsite-apix-error">Sorry, there was a problem loading the API Explorer. This may be a result of an outdated browser/OS. You may need to try a newer machine if you want to make live requests to this API.</div>')};var Rc=!O||9<=Number(Ac),Sc=!qc&&!O||O&&9<=Number(Ac)||qc&&Q("1.9.1"),Tc=O&&!Q("9"),Uc=O||oc||P;function R(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}h=R.prototype;h.Eb=function(){return new R(this.a,this.b)};h.Fb=function(a){return a instanceof R&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};h.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};h.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};h.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
h.Hb=function(a,b){a instanceof R?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};h.Gb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};h.lc=function(a,b){a=a*Math.PI/180;b=b||new R(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Vc(a,b){this.width=a;this.height=b}h=Vc.prototype;h.Ib=function(){return new Vc(this.width,this.height)};h.Ra=function(){return Math.max(this.width,this.height)};h.gb=function(){return Math.min(this.width,this.height)};h.hc=function(){return 2*(this.width+this.height)};h.aspectRatio=function(){return this.width/this.height};h.Jb=function(){return!(this.width*this.height)};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
h.sa=function(a){return this.width<=a.width&&this.height<=a.height};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Wc(a,b){a.width*=b;a.height*=b;return a}h.nc=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Wc(this,a)};
h.oc=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Wc(this,a)};function Xc(a){return a?new S(T(a)):Ta||(Ta=new S)}function Yc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Zc(document,"*",a,b);return d||null}
function $c(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){e=g.className;var k;if(k="function"==typeof e.split)k=0<=w(e.split(/\s+/),c);k&&(a[d++]=g)}a.length=d;return a}return b}
function Zc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):$c(a,b,c,d)[0]||null}function ad(a,b){Xa(b,function(c,d){c&&"object"==typeof c&&c.H&&(c=c.G());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:bd.hasOwnProperty(d)?a.setAttribute(bd[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var bd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function cd(a){a=a.document;a=dd(a)?a.documentElement:a.body;return new Vc(a.clientWidth,a.clientHeight)}function ed(a){return a.scrollingElement?a.scrollingElement:!P&&dd(a)?a.documentElement:a.body||a.documentElement}
function fd(a){return a.parentWindow||a.defaultView}function gd(a,b,c,d){function e(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];Pa(f)&&!hd(f)?x(id(f)?Wa(f):f,e):e(f)}}function U(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function dd(a){return"CSS1Compat"==a.compatMode}function jd(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function kd(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function ld(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}function md(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function hd(a){return u(a)&&0<a.nodeType}function nd(a){return u(a)&&1==a.nodeType}
function od(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function pd(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return qd(b,a)}function qd(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function T(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function rd(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else jd(a),a.appendChild(T(a).createTextNode(String(b)))}function sd(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||sd(a,b,c,d))return!0;a=a.nextSibling}return!1}var td={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ud={IMG:" ",BR:"\n"};
function vd(a){return wd(a)&&xd(a)}function wd(a){return O&&!Q("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function xd(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function yd(a){if(Tc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];zd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Tc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function zd(a,b,c){if(!(a.nodeName in td))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ud)b.push(ud[a.nodeName]);else for(a=a.firstChild;a;)zd(a,b,c),a=a.nextSibling}function id(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==t(a))return"function"==typeof a.item}return!1}
function Ad(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Bd(a,function(f){var g;(g=!e||f.nodeName==e)&&!(g=!c)&&(g="string"===typeof f.className)&&(g=0<=w(f.className.split(/\s+/),c));return g},!0,d)}function Bd(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function S(a){this.a=a||r.document||document}h=S.prototype;h.Ha=Xc;h.pc=function(a){this.a=a};h.Da=function(){return this.a};
h.aa=function(a){return"string"===typeof a?this.a.getElementById(a):a};h.eb=function(a){return"string"===typeof a?this.a.getElementById(a):a};h.ga=S.prototype.aa;h.wb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};h.ba=function(a,b,c){return $c(this.a,a,b,c)};h.Ja=function(a,b,c){return Zc(this.a,a,b,c)};h.Ka=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):$c(document,"*",a,b)};h.Ia=function(a,b){return Yc(a,b||this.a)};
h.fb=function(a,b){return Yc(a,b||this.a)};h.ha=S.prototype.ba;h.tc=ad;h.jb=function(a){return cd(a||fd(this.a)||window)};h.Ea=function(){var a=fd(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=cd(a).height,dd(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
h.Z=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),g=e[1];if(!Rc&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Db(g.name),'"');if(g.type){f.push(' type="',Db(g.type),'"');var k={};$a(k,g);delete k.type;g=k}f.push(">");f=f.join("")}f=U(d,f);g&&("string"===typeof g?f.className=g:Array.isArray(g)?f.className=g.join(" "):ad(f,g));2<e.length&&gd(d,f,e,2);return f};h.ia=S.prototype.Z;h.vb=function(a){return this.a.createTextNode(String(a))};
h.ma=function(a,b,c){var d=this.a;c=!!c;for(var e=U(d,"TABLE"),f=e.appendChild(U(d,"TBODY")),g=0;g<a;g++){for(var k=U(d,"TR"),l=0;l<b;l++){var n=U(d,"TD");c&&rd(n,"\u00a0");k.appendChild(n)}f.appendChild(k)}return e};h.mc=function(a){var b=this.a;var c=U(b,"DIV");O?(a=zb(Ab,a),Cb(c,a),c.removeChild(c.firstChild)):Cb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};h.Sb=function(){return dd(this.a)};
h.Ga=function(){return ed(this.a)};h.Fa=function(){var a=this.a,b=ed(a);a=fd(a);return O&&Q("10")&&a.pageYOffset!=b.scrollTop?new R(b.scrollLeft,b.scrollTop):new R(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};h.va=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};h.tb=function(a,b){a.appendChild(b)};h.sb=function(a,b){gd(T(a),a,arguments,1)};h.ub=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.kc=jd;h.Rb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};h.Qb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};h.Pb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};h.xb=kd;h.yb=ld;h.ta=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return kd(a)}};h.Aa=function(a){return Sc&&void 0!=a.children?a.children:Ua(a.childNodes,function(b){return 1==b.nodeType})};
h.La=function(a){return void 0!==a.firstElementChild?a.firstElementChild:md(a.firstChild,!0)};h.Pa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:md(a.lastChild,!1)};h.Sa=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:md(a.nextSibling,!0)};h.bb=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:md(a.previousSibling,!1)};
h.Ta=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};h.cb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};h.Wb=hd;h.Tb=nd;h.Zb=function(a){return u(a)&&a.window==a};h.ab=function(a){var b;if(Uc&&!(O&&Q("9")&&!Q("10")&&r.SVGElement&&a instanceof r.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return nd(b)?b:null};
h.contains=od;
h.la=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(O&&!(9<=Number(Ac))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?qd(a,b):!c&&od(e,b)?-1*pd(a,b):!d&&od(f,a)?pd(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=T(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(r.Range.START_TO_END,a)};h.pa=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],g=arguments[b];g;)f.unshift(g),g=g.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){g=d[0][b];for(var k=1;k<c;k++)if(g!=d[k][b])return f;f=g}return f};h.Ya=T;h.Ma=function(a){return a.contentDocument||a.contentWindow.document};
h.Na=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?fd(c):window}else d=null;b=d}return b}catch(e){}return null};h.wc=rd;h.Xa=function(a){if("outerHTML"in a)return a.outerHTML;var b=U(T(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};h.qa=function(a,b){var c=[];return sd(a,b,c,!0)?c[0]:void 0};h.ra=function(a,b){var c=[];sd(a,b,c,!1);return c};h.Vb=vd;h.rc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
h.Ub=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!wd(a)||xd(a)):vd(a))&&O){var c;"function"!=t(a.getBoundingClientRect)||O&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};h.hb=yd;h.Va=function(a){return yd(a).length};
h.Wa=function(a,b){b=b||T(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(yd(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
h.Ua=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in td))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in ud)d+=ud[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);u(c)&&(c.jc=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};h.Xb=id;h.ya=Ad;h.xa=function(a,b,c){return Ad(a,null,b,c)};h.wa=Bd;h.za=function(a){return a.getContext("2d")};var Cd={};function Dd(a,b){var c=Cd[a];if(void 0!==c&&(!c.P||Date.now()<=c.P+3E5))return c.p;c=new Promise(function(e,f){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);f(g)};document.head.appendChild(b)});var d={P:0,p:c};c.catch(function(){return d.P=+new Date});Cd[a]=d;return c};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Ed=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Ed&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function V(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}qa(V,HTMLElement);V.prototype.R=function(){console.warn(this.tagName,"has not implemented update")};V.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
V.prototype.J=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Fd(a,b){b=a(b||Gd,void 0,void 0);a=Xc();a=U(a.a,"DIV");if(u(b))if(b instanceof N){if(b.w!==hc)throw Error("Sanitized content was not of kind HTML.");b=E(b.toString(),b.S||null)}else b=vb("zSoyz");else b=vb(String(b));Cb(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Gd={};function Hd(){this.u=this.u;this.b=this.b}h=Hd.prototype;h.u=!1;h.ca=function(){return this.u};h.Ca=Hd.prototype.ca;h.dispose=function(){this.u||(this.u=!0,this.N())};h.ic=function(a){a=Qa(Id,a);this.u?a():(this.b||(this.b=[]),this.b.push(a))};h.N=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Id(a){a&&"function"==typeof a.dispose&&a.dispose()};var Jd=!O||9<=Number(Ac),Kd=!O||9<=Number(Ac),Ld=O&&!Q("9"),Md=function(){if(!r.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{r.addEventListener("test",La,b),r.removeEventListener("test",La,b)}catch(c){}return a}();function Nd(a,b){this.type=a;this.a=this.target=b;this.I=this.c=!1}Nd.prototype.f=function(){this.c=!0};Nd.prototype.b=function(){this.I=!0};function W(a,b){Nd.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.j=this.i=0;this.key="";this.g=this.h=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.s=null;this.J=!1;this.pointerId=0;this.pointerType="";this.m=null;a&&this.init(a,b)}Sa(W,Nd);var Od=[1,4,2],Pd={2:"touch",3:"pen",4:"mouse"};
W.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(qc){a:{try{lc(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.i=P||void 0!==a.offsetX?a.offsetX:a.layerX,this.j=P||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.h=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.J=rc?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||
0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Pd[a.pointerType]||"";this.s=a.state;this.m=a;a.defaultPrevented&&this.b()};W.prototype.R=function(){return(Jd?0==this.m.button:"click"==this.type?!0:!!(this.m.button&Od[0]))&&!(P&&rc&&this.ctrlKey)};W.prototype.f=function(){W.K.f.call(this);this.m.stopPropagation?this.m.stopPropagation():this.m.cancelBubble=!0};
W.prototype.b=function(){W.K.b.call(this);var a=this.m;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ld)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Qd="closure_listenable_"+(1E6*Math.random()|0),Rd=0;function Sd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Rd;this.C=this.M=!1}function Td(a){a.C=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Ud(a){this.src=a;this.a={};this.b=0}h=Ud.prototype;h.Ab=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};h.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Vd(a,b,d,e);-1<g?(b=a[g],c||(b.M=!1)):(b=new Sd(b,this.src,f,!!d,e),b.M=c,a.push(b));return b};
h.Cb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Vd(e,b,c,d);return-1<b?(Td(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};h.Db=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Td(d[e]);delete this.a[c];this.b--}return b};h.Qa=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
h.Bb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ya(this.a,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};function Vd(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Wd="closure_lm_"+(1E6*Math.random()|0),Xd={},Yd=0;function Zd(a,b,c,d,e){if(d&&d.once)return $d(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Zd(a,b[f],c,d,e);return null}c=ae(c);return a&&a[Qd]?be(a,b,c,u(d)?!!d.capture:!!d,e):ce(a,b,c,!1,d,e)}
function ce(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=u(e)?!!e.capture:!!e,k=de(a);k||(a[Wd]=k=new Ud(a));c=k.add(b,c,d,g,f);if(c.a)return c;d=ee();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Md||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(fe(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Yd++;return c}
function ee(){var a=ge,b=Kd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function $d(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)$d(a,b[f],c,d,e);return null}c=ae(c);return a&&a[Qd]?a.I(b,c,u(d)?!!d.capture:!!d,e):ce(a,b,c,!0,d,e)}
function he(a){if("number"!==typeof a&&a&&!a.C){var b=a.src;if(b&&b[Qd])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(fe(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Yd--;if(c=de(b)){d=a.type;if(d in c.a){var e=c.a[d],f=w(e,a),g;(g=0<=f)&&Array.prototype.splice.call(e,f,1);g&&(Td(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Wd]=null)}else Td(a)}}}
function fe(a){return a in Xd?Xd[a]:Xd[a]="on"+a}function ie(a,b,c,d){var e=!0;if(a=de(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.C&&(f=je(f,d),e=e&&!1!==f)}return e}function je(a,b){var c=a.listener,d=a.b||a.src;a.M&&he(a);return c.call(d,b)}
function ge(a,b){if(a.C)return!0;if(!Kd){var c=b||Ka("window.event");b=new W(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.a;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.a=c[e];var f=ie(c[e],a,!0,b);d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.a=c[e],f=ie(c[e],a,!1,b),d=d&&f}return d}return je(a,new W(b,this))}
function de(a){a=a[Wd];return a instanceof Ud?a:null}var ke="__closure_events_fn_"+(1E9*Math.random()>>>0);function ae(a){if("function"==t(a))return a;a[ke]||(a[ke]=function(b){return a.handleEvent(b)});return a[ke]};function le(a){Hd.call(this);this.c=a;this.a={}}Sa(le,Hd);var me=[];function X(a,b,c,d){be(a,b,c,d,void 0)}h=le.prototype;h.cc=function(a,b,c,d,e){return be(this,a,b,c,d,e)};function be(a,b,c,d,e,f){Array.isArray(c)||(c&&(me[0]=c.toString()),c=me);for(var g=0;g<c.length;g++){var k=Zd(b,c[g],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}function ne(a,b){oe(a,document.body,"devsite-sitemask-hidden",b,void 0)}h.bc=function(a,b,c,d,e){return oe(this,a,b,c,d,e)};
function oe(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)oe(a,b,c[g],d,e,f);else{b=$d(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.dc=function(a,b,c,d){be(b,a,c,d,this.c||this);return this};h.ec=function(a,b,c,d,e){be(b,a,c,d,e||this.c||this);return this};h.zb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function pe(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)pe(a,b,c[g],d,e,f);else d=d||a.handleEvent,e=u(e)?!!e.capture:!!e,f=f||a.c||a,d=ae(d),e=!!e,b&&b[Qd]?c=b.s(c,d,e,f):b?(b=de(b))?(c=b.a[c.toString()],b=-1,c&&(b=Vd(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(he(c),delete a.a[c.key])}h.zc=function(a,b,c,d,e){pe(b,a,c,d,e||this.c||this,this);return this};function qe(a){Xa(a.a,function(b,c){this.a.hasOwnProperty(c)&&he(b)},a);a.a={}}h.N=function(){le.K.N.call(this);qe(this)};
h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function re(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||r,e=d.document,f=a.nonce||Ga(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ka("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var k=JSON.stringify(b);(g=1200>=k.length)&&(a.psdJson=k)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);else{d=
c+"/load.js?";for(var l in a)b=a[l],null==b||u(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=Xc(e);a=U(a.a,"SCRIPT");f&&a.setAttribute("nonce",f);a.src=cb(new y(ab,d));(f=Ga())&&a.setAttribute("nonce",f);e.body.appendChild(a)}}Fa("userfeedback.api.startFeedback",re);function Y(){var a=V.call(this,["devsite-apix-snippets"])||this;a.a=null;a.f=null;a.c=null;a.i=null;a.g=null;a.h=null;a.b=new le;return a}qa(Y,V);h=Y.prototype;
h.connectedCallback=function(){var a=this;if(document.body.hasAttribute("block-apix"))kd(this);else if(se(this),Y.a)this.V("previous error");else{var b=this.querySelectorAll(".apis-explorer");1<b.length&&console.warn("Multiple APIs Explorer tags in same, some features may be missing for others.");this.f=b[0];0<b.length&&function(){var c;return Da(function(d){switch(d.a){case 1:return d.c=2,p(d,te(),4);case 4:return p(d,ue(a),5);case 5:return p(d,ve(a),6);case 6:"#try-it"==window.location.hash&&a.v();
d.a=0;d.c=0;break;case 2:c=wa(d),a.V(c),d.a=0}})}()}};h.V=function(a){console.error("Error loading the APIs Explorer widget",a);a=ja(this.querySelectorAll(".apis-explorer"));for(var b=a.next();!b.done;b=a.next())b.value.appendChild(Fd(Qc))};function ve(a){var b;return Da(function(c){if(1==c.a)return we()?p(c,apix.init(a),2):c.return(Promise.reject());a.c&&(b=a.g,b.style.removeProperty("display"),xe(a),ye(a));c.a=0})}
function te(){var a;return Da(function(b){switch(b.a){case 1:if(we())return b.return(Promise.resolve());if(!ze){var c=new URL(document.location.toString());a=/\.corp\.google\.com$|\.googlers\.com$|^localhost$/.test(c.hostname)?"https://api-explorer.googleplex.com/apix-embedder.js":"https://explorer.apis.google.com/apix-embedder.js";var d=void 0===d?null:d;c=a instanceof I?new I(a):new I(a,void 0);var e=document.createElement("script");e.src=c.toString();d&&(e.type=d);ze=Dd(c.toString(),e)}b.c=2;return p(b,
ze,4);case 4:b.a=3;b.c=0;break;case 2:return wa(b),Y.a=!0,b.return(Promise.reject("Error injecting APIx script"));case 3:return we()?b.return(Promise.resolve()):(Y.a=!0,b.return(Promise.reject("APIx script not properly injected")))}})}h.disconnectedCallback=function(){var a=this;return Da(function(b){return 1==b.a?(a.a=null,a.f=null,a.i=null,a.g=null,a.h=null,a.c=null,qe(a.b),Z===a&&(Z=null),we()?p(b,apix.dispose(a),2):b.B(2)):b.return(Promise.resolve())})};
function ue(a){var b=a.querySelectorAll(".devsite-apix");0!==b.length&&(1<b.length&&console.warn("Too many `.devsite-apix`, using first."),Z=a,a.a=b[0],a.a.insertBefore(Fd(Oc),a.a.firstChild),a.c=Fd(Nc),a.i=a.c.querySelector(".devsite-hide-apix"),a.g=a.c.querySelector(".devsite-fullscreen-apix"),a.h=a.c.querySelector(".devsite-dock-apix"),a.g.style.display="none",a.a.insertBefore(a.c,a.a.firstChild),X(a.b,document.body,"click",function(c){c.target.classList.contains("devsite-show-apix")&&a.show();
(c=Ad(c.target,"A"))&&"#try-it"===c.hash&&(window.matchMedia("screen and (max-width: 1200px)").matches||a.v())}),X(a.b,a.i,"click",function(){a.W()}),X(a.b,window,"popstate",function(){xe(a)}),X(a.b,a.g,"click",function(){a.v()}),X(a.b,a.h,"click",function(){a.F()}),X(a.b,window,"devsite-apix-observation",function(c){c=c.m.detail;switch(c.action){case "fullscreen":a.v();break;case "setMethod":c.method&&a.setMethod(c.method);break;case "setParams":c.params&&c.tag&&a.setParams(c.params,c.tag)}}),X(a.b,
window,"devsite-sticky-scroll",function(c){c=c.m.detail;Ae(a,c.offset,c.contentMargin,c.contentHeight)}),a.show())}
function se(a){var b=a.querySelector("section#try-it")||a.querySelector("section#apix"),c=!0;b?a=b.querySelector("div#embedded-explorer"):(a=a.querySelector("div#embedded-explorer"))&&!Be(a,"data-load-dynamic-snippets")&&(c=!1);if(a){var d=Be(a,"data-allow-tryit"),e=Be(a,"data-load-dynamic-snippets");d||e||(d=!0);if(d||e){var f=a.getAttribute("data-discoveryUrl"),g=a.getAttribute("data-method");if(!f){f=a.getAttribute("data-service");var k=a.getAttribute("data-version");f="appengine"===f?"https://"+
encodeURIComponent(f)+".googleapis.com/$discovery/google_rest?version="+encodeURIComponent(k):"https://content.googleapis.com/discovery/v1/apis/"+encodeURIComponent(f)+"/"+encodeURIComponent(k)+"/rest"}c=Fd(Mc,{$:f,method:g,fa:c});e?(d&&a.parentElement.insertBefore(c,a.nextSibling),b=Fd(Pc,{ea:a.getAttribute("data-service"),version:a.getAttribute("data-version"),da:g}),ld(b,a)):d&&(b?ld(c,b):(a.parentElement.insertBefore(c,a.nextSibling),kd(a)))}}}
function ye(a){if(a.a){var b=a.f;b&&b.setWideLayout&&(b.addFeedbackFn&&b.addFeedbackFn(function(){var c={productId:"5020320",locale:DevsiteApp.getLocale(),bucket:"Explorer",productVersion:apix.version,callback:function(){Ce()}};re(c,{context:"",type:""})}),b.addFullscreenFn&&b.addFullscreenFn(function(){a.v()}))}}function Ce(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return kd(a)})}
function Be(a,b){a=a.getAttribute(b);return!!a&&"true"===a.toLowerCase()||!1}h.show=function(){var a=document.querySelector("devsite-toc .devsite-show-apix");a&&a.setAttribute("disabled","");document.body.classList.add("devsite-has-apix")};h.W=function(){this.F();var a=document.querySelector("devsite-toc .devsite-show-apix");a&&a.removeAttribute("disabled");document.body.classList.remove("devsite-has-apix")};
h.v=function(){var a,b=Rb();if(a="apix="+encodeURIComponent("true")){var c=b.indexOf("#");0>c&&(c=b.length);var d=b.indexOf("?");if(0>d||d>c){d=c;var e=""}else e=b.substring(d+1,c);b=[b.substr(0,d),e,b.substr(c)];c=b[1];b[1]=a?c?c+"&"+a:a:c;a=b[0]+(b[1]?"?"+b[1]:"")+b[2]}else a=b;history.replaceState(null,"",a);xe(this)};h.F=function(){this.show();var a=Rb();history.replaceState(null,"",a);xe(this)};
function xe(a){if(a.a){var b=null!==Pb(),c=a.f;c&&c.setWideLayout&&(b?(a.show(),ne(a.b,function(){a.F()}),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})),a.a.classList.add("dialog"),c.setWideLayout(!0)):(a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),a.a.classList.remove("dialog"),c.setWideLayout(!1)))}}h.setParams=function(a,b){this.show();this.f.setParams(a,b)};h.setMethod=function(a){this.show();this.f.setMethod(a)};
function Ae(a,b,c,d){a.a&&window.requestAnimationFrame(function(){void 0!==b&&(a.a.style.transform="translate3d(0, -"+b+"px, 0)");void 0!==c&&(a.a.style.top=c+"px");void 0!==d&&(a.a.style.height=d+"px")})}function we(){return void 0!==window.apix&&!!apix.init&&!!apix.dispose}m.Object.defineProperties(Y,{a:{configurable:!0,enumerable:!0,get:function(){return De},set:function(a){De=a}}});Y.prototype.setMethod=Y.prototype.setMethod;Y.prototype.setParams=Y.prototype.setParams;Y.prototype.dock=Y.prototype.F;
Y.prototype.fullscreen=Y.prototype.v;Y.prototype.hide=Y.prototype.W;Y.prototype.show=Y.prototype.show;Y.prototype.disconnectedCallback=Y.prototype.disconnectedCallback;Y.prototype.connectedCallback=Y.prototype.connectedCallback;var ze=null,De=!1,Z=null;Fa("devsite.apix.setMethod",function(a){Z&&Z.setMethod(a)});Fa("devsite.apix.setParams",function(a,b){Z&&Z.setParams(a,b)});try{window.customElements.define("devsite-apix",Y)}catch(a){console.warn("devsite.app.customElement.DevsiteAPIx",a)};}).call(this);
