(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ba(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ba(this);function ca(){ca=function(){};p.Symbol||(p.Symbol=ha)}function ia(a,b){this.a=a;n(this,"description",{configurable:!0,writable:!0,value:b})}ia.prototype.toString=function(){return this.a};
var ha=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ia("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function r(){ca();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ja(aa(this))}});r=function(){}}function ja(a){r();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}
function u(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ka="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},la;if("function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={I:!0},oa={};try{oa.__proto__=na;ma=oa.I;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var pa=la;function qa(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.S=b.prototype}function v(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}}
v("Promise",function(a){function b(e){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{e(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(e){return e instanceof b?e:new b(function(k){k(e)})}if(a)return a;c.prototype.b=function(e){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(e)};var f=p.setTimeout;c.prototype.c=function(e){f(e,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var e=this.a;this.a=[];for(var k=0;k<e.length;++k){var l=
e[k];e[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(e){this.c(function(){throw e;})};b.prototype.c=function(){function e(m){return function(q){l||(l=!0,m.call(k,q))}}var k=this,l=!1;return{resolve:e(this.O),reject:e(this.f)}};b.prototype.O=function(e){if(e===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.P(e);else{a:switch(typeof e){case "object":var k=null!=e;break a;case "function":k=!0;break a;default:k=!1}k?this.N(e):this.h(e)}};
b.prototype.N=function(e){var k=void 0;try{k=e.then}catch(l){this.f(l);return}"function"==typeof k?this.T(k,e):this.h(e)};b.prototype.f=function(e){this.i(2,e)};b.prototype.h=function(e){this.i(1,e)};b.prototype.i=function(e,k){if(0!=this.b)throw Error("Cannot settle("+e+", "+k+"): Promise already settled in state"+this.b);this.b=e;this.g=k;this.o()};b.prototype.o=function(){if(null!=this.a){for(var e=0;e<this.a.length;++e)h.b(this.a[e]);this.a=null}};var h=new c;b.prototype.P=function(e){var k=this.c();
e.s(k.resolve,k.reject)};b.prototype.T=function(e,k){var l=this.c();try{e.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(e,k){function l(t,x){return"function"==typeof t?function(da){try{m(t(da))}catch(ea){q(ea)}}:x}var m,q,fa=new b(function(t,x){m=t;q=x});this.s(l(e,m),l(k,q));return fa};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.s=function(e,k){function l(){switch(m.b){case 1:e(m.g);break;case 2:k(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?h.b(l):this.a.push(l)};b.resolve=d;b.reject=function(e){return new b(function(k,l){l(e)})};b.race=function(e){return new b(function(k,l){for(var m=u(e),q=m.next();!q.done;q=m.next())d(q.value).s(k,l)})};b.all=function(e){var k=u(e),l=k.next();return l.done?d([]):new b(function(m,q){function fa(da){return function(ea){t[da]=ea;x--;0==x&&m(t)}}var t=[],x=0;do t.push(void 0),x++,d(l.value).s(fa(t.length-1),q),l=k.next();while(!l.done)})};return b});
function ra(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function sa(){this.i=!1;this.f=null;this.h=void 0;this.a=1;this.g=this.c=0;this.o=this.b=null}function ta(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}g=sa.prototype;g.w=function(a){this.h=a};function ua(a,b){a.b={C:b,G:!0};a.a=a.c||a.g}g.return=function(a){this.b={return:a};this.a=this.g};g.nb=function(a){this.b={m:a};this.a=this.g};
function w(a,b,c){a.a=c;return{value:b}}g.Bb=function(a,b){a=u(a);var c=a.next();ra(c);if(c.done)this.h=c.value,this.a=b;else return this.f=a,w(this,c.value,b)};g.m=function(a){this.a=a};g.xb=function(a){this.c=0;this.g=a||0};function va(a,b){a.a=b;a.c=0}function wa(a){a.c=0;var b=a.b.C;a.b=null;return b}g.aa=function(a,b,c){c?this.o[c]=this.b:this.o=[this.b];this.c=a||0;this.g=b||0};
g.ob=function(a,b){b=this.o.splice(b||0)[0];(b=this.b=this.b||b)?b.G?this.a=this.c||this.g:void 0!=b.m&&this.g<b.m?(this.a=b.m,this.b=null):this.a=this.g:this.a=a};g.ha=function(a){return new xa(a)};function xa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}xa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ya(a){this.a=new sa;this.b=a}
function za(a,b){ta(a.a);var c=a.a.f;if(c)return Aa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return y(a)}function Aa(a,b,c,d){try{var f=b.call(a.a.f,c);ra(f);if(!f.done)return a.a.i=!1,f;var h=f.value}catch(e){return a.a.f=null,ua(a.a,e),y(a)}a.a.f=null;d.call(a.a,h);return y(a)}
function y(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.i=!1,{value:b.value,done:!1}}catch(c){a.a.h=void 0,ua(a.a,c)}a.a.i=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.G)throw b.C;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function Ba(a){this.next=function(b){ta(a.a);a.a.f?b=Aa(a,a.a.f.next,b,a.a.w):(a.a.w(b),b=y(a));return b};this.throw=function(b){ta(a.a);a.a.f?b=Aa(a,a.a.f["throw"],b,a.a.w):(ua(a.a,b),b=y(a));return b};this.return=function(b){return za(a,b)};r();this[Symbol.iterator]=function(){return this}}function Ca(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function h(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(h,f)}h(a.next())})}
function z(a){return Ca(new Ba(new ya(a)))}v("Object.setPrototypeOf",function(a){return a||pa});
var Da=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,f){c=b(c,d);f&&Reflect.setPrototypeOf(c,f.prototype);return c}}return function(c,d,f){void 0===f&&(f=c);f=ka(f.prototype||Object.prototype);return Function.prototype.apply.call(c,f,d)||f}}();v("Reflect.construct",function(){return Da});
v("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});var A=this||self;
function Ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Fa(a){var b=Ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function B(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ga(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(d,f,h){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return b.prototype[f].apply(d,e)}};var Ha;var Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in d&&b.call(void 0,d[f],f,a)},Ka=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],f=0,h="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in h){var k=h[e];b.call(void 0,k,e,a)&&(d[f++]=k)}return d};function La(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ma(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Oa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var h=0;h<Na.length;h++)c=Na[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function C(a,b){this.a=a===Pa&&b||"";this.b=Qa}g=C.prototype;g.v=!0;g.u=function(){return this.a.toString()};g.B=!0;g.l=function(){return 1};g.Y=function(a,b){var c=Ra(this).toString();c=Sa.exec(c);var d=c[3]||"";return new C(Pa,c[1]+Ta("?",c[2]||"",a)+Ta("#",d,b))};function Ra(a){return a instanceof C&&a.constructor===C&&a.b===Qa?a.a:"type_error:TrustedResourceUrl"}var Sa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Qa={};
function Ta(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var f=c[d];f=Array.isArray(f)?f:[f];for(var h=0;h<f.length;h++){var e=f[h];null!=e&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(e)))}}return b}var Pa={};var Ua=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Va(a,b){if(b)a=a.replace(Wa,"&amp;").replace(Xa,"&lt;").replace(Ya,"&gt;").replace(Za,"&quot;").replace($a,"&#39;").replace(ab,"&#0;");else{if(!bb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Za,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace($a,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ab,"&#0;"))}return a}
var Wa=/&/g,Xa=/</g,Ya=/>/g,Za=/"/g,$a=/'/g,ab=/\x00/g,bb=/[\x00&<>"']/;function cb(a,b){return a<b?-1:a>b?1:0};function D(a,b){this.a=a===db&&b||"";this.b=eb}D.prototype.v=!0;D.prototype.u=function(){return this.a.toString()};D.prototype.B=!0;D.prototype.l=function(){return 1};var eb={},db={};var E;a:{var fb=A.navigator;if(fb){var gb=fb.userAgent;if(gb){E=gb;break a}}E=""};function F(){this.a="";this.c=hb;this.b=null}F.prototype.B=!0;F.prototype.l=function(){return this.b};F.prototype.v=!0;F.prototype.u=function(){return this.a.toString()};function G(a){return a instanceof F&&a.constructor===F&&a.c===hb?a.a:"type_error:SafeHtml"}function H(a){if(a instanceof F)return a;var b="object"==typeof a,c=null;b&&a.B&&(c=a.l());return ib(Va(b&&a.v?a.u():String(a)),c)}
function jb(a){function b(h){Array.isArray(h)?Ja(h,b):(h=H(h),f.push(G(h).toString()),h=h.l(),0==d?d=h:0!=h&&d!=h&&(d=null))}var c=H(kb),d=c.l(),f=[];Ja(a,b);return ib(f.join(G(c).toString()),d)}function lb(a){return jb(Array.prototype.slice.call(arguments))}var hb={};function ib(a,b){return I(a,b)}function I(a,b){var c=new F;c.a=a;c.b=b;return c}I("<!DOCTYPE html>",0);var kb=I("",0),mb=I("<br>",0);var nb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=G(kb);return!b.parentElement});function ob(a,b){if(nb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=G(b)};function J(a){return a=Va(a,void 0)};var K={},pb={},qb={};function L(){throw Error("Do not instantiate directly");}L.prototype.A=null;L.prototype.toString=function(){return this.F};L.prototype.a=function(){if(this.j!==pb)throw Error("Sanitized content was not of kind URI.");return new D(db,this.toString())};function rb(){L.call(this)}Ga(rb,L);rb.prototype.j=K;function sb(a,b){var c=tb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ub=-1!=E.indexOf("Opera"),M=-1!=E.indexOf("Trident")||-1!=E.indexOf("MSIE"),vb=-1!=E.indexOf("Edge"),wb=-1!=E.indexOf("Gecko")&&!(-1!=E.toLowerCase().indexOf("webkit")&&-1==E.indexOf("Edge"))&&!(-1!=E.indexOf("Trident")||-1!=E.indexOf("MSIE"))&&-1==E.indexOf("Edge"),xb=-1!=E.toLowerCase().indexOf("webkit")&&-1==E.indexOf("Edge");function yb(){var a=A.document;return a?a.documentMode:void 0}var zb;
a:{var Ab="",Bb=function(){var a=E;if(wb)return/rv:([^\);]+)(\)|;)/.exec(a);if(vb)return/Edge\/([\d\.]+)/.exec(a);if(M)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(xb)return/WebKit\/(\S+)/.exec(a);if(ub)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Bb&&(Ab=Bb?Bb[1]:"");if(M){var Cb=yb();if(null!=Cb&&Cb>parseFloat(Ab)){zb=String(Cb);break a}}zb=Ab}var Db=zb,tb={};
function N(a){return sb(a,function(){for(var b=0,c=Ua(String(Db)).split("."),d=Ua(String(a)).split("."),f=Math.max(c.length,d.length),h=0;0==b&&h<f;h++){var e=c[h]||"",k=d[h]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==e[0].length&&0==k[0].length)break;b=cb(0==e[1].length?0:parseInt(e[1],10),0==k[1].length?0:parseInt(k[1],10))||cb(0==e[2].length,0==k[2].length)||cb(e[2],k[2]);e=e[3];k=k[3]}while(0==b)}return 0<=b})}var Eb;
if(A.document&&M){var Fb=yb();Eb=Fb?Fb:parseInt(Db,10)||void 0}else Eb=void 0;var Gb=Eb;function Hb(a){if(null!=a)switch(a.A){case 1:return 1;case -1:return-1;case 0:return 0}return null}function Ib(a){return null!=a&&a.j===K?a:a instanceof F?Jb(G(a).toString(),a.l()):Jb(J(String(String(a))),Hb(a))}var Jb=function(a){function b(c){this.F=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.A=d);return c}}(rb);function Kb(a){return null!=a&&a.j===K?String(String(a.F).replace(Lb,"").replace(Mb,"&lt;")).replace(Nb,Ob):J(String(a))}
function Pb(a){null!=a&&a.j===pb||null!=a&&a.j===qb?a=String(a).replace(O,P):a instanceof D?(a=a instanceof D&&a.constructor===D&&a.b===eb?a.a:"type_error:SafeUrl",a=String(a).replace(O,P)):a instanceof C?a=String(Ra(a).toString()).replace(O,P):(a=String(a),a=Qb.test(a)?a.replace(O,P):"about:invalid#zSoyz");return a}
var Rb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Ob(a){return Rb[a]}
var Sb={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function P(a){return Sb[a]}var Nb=/[\x00\x22\x27\x3c\x3e]/g,O=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Qb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,Lb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Mb=/</g;var Tb=!M||9<=Number(Gb),Ub=!wb&&!M||M&&9<=Number(Gb)||wb&&N("1.9.1"),Vb=M&&!N("9"),Wb=M||ub||xb;function Q(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=Q.prototype;g.Ya=function(){return new Q(this.a,this.b)};g.ba=function(a){return a instanceof Q&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.$a=function(a,b){a instanceof Q?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.Za=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.sb=function(a,b){a=a*Math.PI/180;b=b||new Q(0,0);var c=this.a,d=this.b,f=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*f-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*f+b.b};function Xb(a,b){this.width=a;this.height=b}g=Xb.prototype;g.ab=function(){return new Xb(this.width,this.height)};g.Aa=function(){return Math.max(this.width,this.height)};g.Na=function(){return Math.min(this.width,this.height)};g.pb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.hb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.fa=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Yb(a,b){a.width*=b;a.height*=b;return a}g.ub=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Yb(this,a)};
g.vb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Yb(this,a)};function Zb(a){return a?new R(S(a)):Ha||(Ha=new R)}function $b(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=ac(document,"*",a,b);return d||null}
function bc(a,b,c,d){a=d||a;var f=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(f||c))return a.querySelectorAll(f+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(f){a={};for(var h=d=0,e;e=b[h];h++)f==e.nodeName&&(a[d++]=e);a.length=d;return a}return b}b=a.getElementsByTagName(f||"*");if(c){a={};for(h=d=0;e=b[h];h++){f=e.className;var k;if(k="function"==typeof f.split)k=0<=Ia(f.split(/\s+/),c);k&&(a[d++]=e)}a.length=d;return a}return b}
function ac(a,b,c,d){var f=d||a,h=b&&"*"!=b?String(b).toUpperCase():"";return f.querySelectorAll&&f.querySelector&&(h||c)?f.querySelector(h+(c?"."+c:"")):bc(a,b,c,d)[0]||null}function cc(a,b){Ma(b,function(c,d){c&&"object"==typeof c&&c.v&&(c=c.u());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:dc.hasOwnProperty(d)?a.setAttribute(dc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var dc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function ec(a){a=a.document;a=T(a)?a.documentElement:a.body;return new Xb(a.clientWidth,a.clientHeight)}function fc(a){return a.scrollingElement?a.scrollingElement:!xb&&T(a)?a.documentElement:a.body||a.documentElement}
function U(a){return a.parentWindow||a.defaultView}function gc(a,b,c,d){function f(e){e&&b.appendChild("string"===typeof e?a.createTextNode(e):e)}for(;d<c.length;d++){var h=c[d];Fa(h)&&!hc(h)?Ja(ic(h)?La(h):h,f):f(h)}}function V(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function T(a){return"CSS1Compat"==a.compatMode}function jc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function kc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function W(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function hc(a){return B(a)&&0<a.nodeType}function lc(a){return B(a)&&1==a.nodeType}function mc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function nc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return oc(b,a)}function oc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function S(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function pc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else jc(a),a.appendChild(S(a).createTextNode(String(b)))}function qc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||qc(a,b,c,d))return!0;a=a.nextSibling}return!1}var rc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},X={IMG:" ",BR:"\n"};
function sc(a){return tc(a)&&uc(a)}function tc(a){return M&&!N("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function uc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function vc(a){if(Vb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];wc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Vb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function wc(a,b,c){if(!(a.nodeName in rc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in X)b.push(X[a.nodeName]);else for(a=a.firstChild;a;)wc(a,b,c),a=a.nextSibling}function ic(a){if(a&&"number"==typeof a.length){if(B(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==Ea(a))return"function"==typeof a.item}return!1}
function xc(a,b,c,d){if(!b&&!c)return null;var f=b?String(b).toUpperCase():null;return yc(a,function(h){var e;(e=!f||h.nodeName==f)&&!(e=!c)&&(e="string"===typeof h.className)&&(e=0<=Ia(h.className.split(/\s+/),c));return e},!0,d)}function yc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function R(a){this.a=a||A.document||document}g=R.prototype;g.sa=Zb;g.wb=function(a){this.a=a};g.oa=function(){return this.a};
g.L=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.La=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.U=R.prototype.L;g.Va=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.M=function(a,b,c){return bc(this.a,a,b,c)};g.ua=function(a,b,c){return ac(this.a,a,b,c)};g.va=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):bc(document,"*",a,b)};g.ta=function(a,b){return $b(a,b||this.a)};
g.Ma=function(a,b){return $b(a,b||this.a)};g.V=R.prototype.M;g.zb=cc;g.Pa=function(a){return ec(a||U(this.a)||window)};g.pa=function(){var a=U(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=ec(a).height,T(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var f=d.offsetHeight;d.clientHeight!=f&&(b=c.scrollHeight,f=c.offsetHeight);c=b>a?b>f?b:f:b<f?b:f}else c=0}return c};
g.K=function(a,b,c){var d=this.a,f=arguments,h=String(f[0]),e=f[1];if(!Tb&&e&&(e.name||e.type)){h=["<",h];e.name&&h.push(' name="',J(e.name),'"');if(e.type){h.push(' type="',J(e.type),'"');var k={};Oa(k,e);delete k.type;e=k}h.push(">");h=h.join("")}h=V(d,h);e&&("string"===typeof e?h.className=e:Array.isArray(e)?h.className=e.join(" "):cc(h,e));2<f.length&&gc(d,h,f,2);return h};g.W=R.prototype.K;g.Ua=function(a){return this.a.createTextNode(String(a))};
g.$=function(a,b,c){var d=this.a;c=!!c;for(var f=V(d,"TABLE"),h=f.appendChild(V(d,"TBODY")),e=0;e<a;e++){for(var k=V(d,"TR"),l=0;l<b;l++){var m=V(d,"TD");c&&pc(m,"\u00a0");k.appendChild(m)}h.appendChild(k)}return f};g.tb=function(a){var b=this.a;var c=V(b,"DIV");M?(a=lb(mb,a),ob(c,a),c.removeChild(c.firstChild)):ob(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.fb=function(){return T(this.a)};
g.ra=function(){return fc(this.a)};g.qa=function(){var a=this.a,b=fc(a);a=U(a);return M&&N("10")&&a.pageYOffset!=b.scrollTop?new Q(b.scrollLeft,b.scrollTop):new Q(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ia=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Ra=function(a,b){a.appendChild(b)};g.Qa=function(a,b){gc(S(a),a,arguments,1)};g.Sa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.rb=jc;g.eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.cb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.bb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Wa=kc;g.Xa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ga=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return kc(a)}};
g.na=function(a){return Ub&&void 0!=a.children?a.children:Ka(a.childNodes,function(b){return 1==b.nodeType})};g.wa=function(a){return void 0!==a.firstElementChild?a.firstElementChild:W(a.firstChild,!0)};g.za=function(a){return void 0!==a.lastElementChild?a.lastElementChild:W(a.lastChild,!1)};g.Ba=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:W(a.nextSibling,!0)};g.Ja=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:W(a.previousSibling,!1)};
g.Ca=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ka=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.kb=hc;g.gb=lc;g.mb=function(a){return B(a)&&a.window==a};g.Ia=function(a){var b;if(Wb&&!(M&&N("9")&&!N("10")&&A.SVGElement&&a instanceof A.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return lc(b)?b:null};
g.Ta=mc;
g.Z=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(M&&!(9<=Number(Gb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var f=a.parentNode,h=b.parentNode;return f==h?oc(a,b):!c&&mc(f,b)?-1*nc(a,b):!d&&mc(h,a)?nc(b,a):(c?a.sourceIndex:f.sourceIndex)-(d?b.sourceIndex:h.sourceIndex)}d=S(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(A.Range.START_TO_END,a)};g.ca=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],f=Infinity;for(b=0;b<c;b++){for(var h=[],e=arguments[b];e;)h.unshift(e),e=e.parentNode;d.push(h);f=Math.min(f,h.length)}h=null;for(b=0;b<f;b++){e=d[0][b];for(var k=1;k<c;k++)if(e!=d[k][b])return h;h=e}return h};g.Ha=S;g.xa=function(a){return a.contentDocument||a.contentWindow.document};
g.ya=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?U(c):window}else d=null;b=d}return b}catch(f){}return null};g.Ab=pc;g.Ga=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(S(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.da=function(a,b){var c=[];return qc(a,b,c,!0)?c[0]:void 0};g.ea=function(a,b){var c=[];qc(a,b,c,!1);return c};g.jb=sc;g.yb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.ib=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!tc(a)||uc(a)):sc(a))&&M){var c;"function"!=Ea(a.getBoundingClientRect)||M&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Oa=vc;g.Ea=function(a){return vc(a).length};
g.Fa=function(a,b){b=b||S(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(vc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Da=function(a,b,c){a=[a];for(var d=0,f=null;0<a.length&&d<b;)if(f=a.pop(),!(f.nodeName in rc))if(3==f.nodeType){var h=f.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=h.length}else if(f.nodeName in X)d+=X[f.nodeName].length;else for(h=f.childNodes.length-1;0<=h;h--)a.push(f.childNodes[h]);B(c)&&(c.qb=f?f.nodeValue.length+b-d-1:0,c.node=f);return f};g.lb=ic;g.la=xc;g.ka=function(a,b,c){return xc(a,null,b,c)};g.ja=yc;g.ma=function(a){return a.getContext("2d")};function zc(a){var b={credentials:"omit"};b=void 0===b?{}:b;var c={method:"GET",credentials:"include"},d;for(d in b)"headers"==d?c.headers=b[d]:c[d]=b[d];return window.fetch(a,c).then(function(f){return 200===f.status||404===f.status?Promise.resolve(f):Promise.reject(f)}).then(function(f){return c.headers&&c.headers.get("X-DevSite-Partial-Request")&&!f.headers.get("X-DevSite-Partial-Response")?Promise.reject(f):Promise.resolve(f)}).then(function(f){var h=f.headers.get("Content-Type");return h&&-1!==
h.indexOf("application/json")?f.text():Promise.reject(f)})};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Ac=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Ac&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Y(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}qa(Y,HTMLElement);Y.prototype.h=function(){console.warn(this.tagName,"has not implemented update")};Y.prototype.f=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Y.prototype.g=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Bc(a){var b=a||Cc;a=b.R;var c=b.J;b='<section id="examples"><h2>Examples</h2>';c&&(b+='<p class="note">',c='<b>Note:</b> The code examples available for this method do not represent all supported programming languages (see the <a href="'+(Kb(Pb(c))+'">client libraries page</a> for a list of supported languages).'),b=b+c+"</p>");b+='<div id="code-sample" class="ds-selector-tabs" data-ds-scope="code-sample">';c=a.length;for(var d=0;d<c;d++){var f=a[d];b+="<section><h3>"+Ib(f.lang)+"</h3>";
if(f.H)for(var h=f.H,e=h.length,k=0;k<e;k++){var l=h[k];l.name&&l.url&&(b+="<p>",l='Uses the <a target="_blank" href="'+(Kb(Pb(l.url))+'">'+(Ib(l.name)+"</a>.")),b+=l,b+="</p>")}b+='<pre class="prettyprint">'+Ib(f.D)+"</pre></section>"}b=Jb(b+"</div></section>");a=Zb();a=V(a.a,"DIV");if(B(b))if(b instanceof L){if(b.j!==K)throw Error("Sanitized content was not of kind HTML.");b=I(b.toString(),b.A||null)}else b=H("zSoyz");else b=H(String(b));ob(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&
(a=b));return a}var Cc={};function Z(){var a=Y.call(this)||this;a.b="";a.c="";a.a="";return a}qa(Z,Y);Z.prototype.connectedCallback=function(){var a=this;this.b=this.getAttribute("data-service-name");this.c=this.getAttribute("data-service-version");this.a=this.getAttribute("data-method-id");Z.a?Dc(this,"previous error"):function(){var b;return z(function(c){if(1==c.a)return c.c=2,w(c,Ec(a),4);if(2!=c.a)return va(c,0);b=wa(c);Dc(a,b);c.a=0})}()};
function Dc(a,b){console.error("Error loading the dynamic code snippets widget",b);a.innerText="Error loading code samples"}
function Ec(a){var b,c,d,f,h,e;return z(function(k){switch(k.a){case 1:return k.c=2,w(k,Fc(a),4);case 4:b=k.h;va(k,3);break;case 2:return c=wa(k),console.debug("Not showing code examples because dynamic snippets config was not\n              found",c),k.return(Promise.resolve());case 3:if(d=b.codeFragment)f=d.clientLibrariesUrl,h=Object.entries(d).filter(function(l){l=u(l);l.next();return"object"===typeof l.next().value}).map(function(l){var m=u(l);l=m.next().value;m=m.next().value;return{lang:l,
D:m.fragment,H:m.libraries}}).filter(function(l){return!!l.D}),e=Bc({J:f,R:h}),a.appendChild(e);return k.return(Promise.resolve())}})}function Fc(a){return z(function(b){switch(b.a){case 1:var c=new URL(document.location.toString());if(!/\.corp\.google\.com$|\.googlers\.com$|^localhost$/.test(c.hostname)){b.m(2);break}b.c=3;return w(b,Gc(a,!0),5);case 5:return b.return(b.h);case 3:wa(b);case 2:return b.return(Gc(a,!1))}})}
function Gc(a,b){var c,d;return z(function(f){if(1==f.a)return c="https://storage.googleapis.com/apisnippets"+(b?"-staging":"")+"/public/"+a.b+"/"+a.c+"/0/"+a.a+".frag.json",w(f,zc(c),2);d=f.h;try{return f.return(JSON.parse(d))}catch(h){return console.error("Failed to parse snippet response JSON",h),f.return(Promise.reject("Failed to parse snippet response JSON"))}})}p.Object.defineProperties(Z,{a:{configurable:!0,enumerable:!0,get:function(){return Hc},set:function(a){Hc=a}}});
Z.prototype.connectedCallback=Z.prototype.connectedCallback;var Hc=!1;try{window.customElements.define("devsite-apix-snippets",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteAPIxSnippets",a)};}).call(this);
