(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ba(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ba(this);function ca(){ca=function(){};q.Symbol||(q.Symbol=da)}function ea(a,b){this.a=a;p(this,"description",{configurable:!0,writable:!0,value:b})}ea.prototype.toString=function(){return this.a};
var da=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ea("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function fa(){ca();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}});fa=function(){}}function ha(a){fa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
function ia(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ja="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ka;if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={L:!0},na={};try{na.__proto__=ma;la=na.L;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var oa=ka;function pa(a,b){a.prototype=ja(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.w=b.prototype}function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Object.setPrototypeOf",function(a){return a||oa});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ja(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return qa});
r("WeakMap",function(a){function b(l){this.a=(h+=Math.random()+1).toString();if(l){l=ia(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,k)){var m=new c;p(l,k,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(G){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,k))throw Error("WeakMap key fail: "+l);l[k][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,k)?l[k][this.a]:void 0};b.prototype.has=function(l){return d(l)&&t(l,k)&&t(l[k],this.a)};
b.prototype.delete=function(l){return d(l)&&t(l,k)&&t(l[k],this.a)?delete l[k][this.a]:!1};return b});
r("Map",function(a){function b(){var h={};return h.i=h.next=h.head=h}function c(h,l){var m=h.a;return ha(function(){if(m){for(;m.head!=h.a;)m=m.i;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++k,f.set(l,m)):m="p_"+l;var n=h.b[m];if(n&&t(h.b,m))for(h=0;h<n.length;h++){var G=n[h];if(l!==l&&G.key!==G.key||l===G.key)return{id:m,list:n,index:h,f:G}}return{id:m,list:n,
index:-1,f:void 0}}function e(h){this.b={};this.a=b();this.size=0;if(h){h=ia(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(ia([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(G){return!1}}())return a;fa();var f=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.b[m.id]=[]);m.f?m.f.value=l:(m.f={next:this.a,i:this.a.i,head:this.a,key:h,value:l},m.list.push(m.f),this.a.i.next=m.f,this.a.i=m.f,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.f&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.f.i.next=h.f.next,h.f.next.i=h.f.i,h.f.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.i=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).f};e.prototype.get=function(h){return(h=d(this,h).f)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=
n.value,h.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});var u=this||self;function ra(){}
function sa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ta(a){var b=sa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"function"==sa(a)}function w(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ua(a,b,c){return a.call.apply(a.bind,arguments)}
function va(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x=ua:x=va;return x.apply(null,arguments)}
function wa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var xa=Date.now||function(){return+new Date};function y(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Y=function(d,e,f){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[e].apply(d,k)}};var ya;var za=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Ba=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,k=0;k<c;k++)if(k in f){var h=f[k];b.call(void 0,h,k,a)&&(d[e++]=h)}return d};function Ca(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Da(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Ea="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Fa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ea.length;f++)c=Ea[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Ga=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ha(a,b){if(b)a=a.replace(Ia,"&amp;").replace(Ja,"&lt;").replace(Ka,"&gt;").replace(La,"&quot;").replace(Ma,"&#39;").replace(Na,"&#0;");else{if(!Oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ia,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ja,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ka,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(La,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ma,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Na,"&#0;"))}return a}
var Ia=/&/g,Ja=/</g,Ka=/>/g,La=/"/g,Ma=/'/g,Na=/\x00/g,Oa=/[\x00&<>"']/;function Pa(a,b){return a<b?-1:a>b?1:0};function z(a){this.b=Qa===Qa&&a||"";this.c=Ra}z.prototype.G=!0;z.prototype.F=function(){return this.b.toString()};z.prototype.J=!0;z.prototype.a=function(){return 1};var Ra={},Qa={};var A;a:{var Sa=u.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){A=Ta;break a}}A=""};function B(){this.b="";this.g=Ua;this.c=null}B.prototype.J=!0;B.prototype.a=function(){return this.c};B.prototype.G=!0;B.prototype.F=function(){return this.b.toString()};function C(a){return a instanceof B&&a.constructor===B&&a.g===Ua?a.b:"type_error:SafeHtml"}function D(a){if(a instanceof B)return a;var b="object"==typeof a,c=null;b&&a.J&&(c=a.a());return Va(Ha(b&&a.G?a.F():String(a)),c)}
function Wa(a){function b(f){Array.isArray(f)?Aa(f,b):(f=D(f),e.push(C(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=D(Xa),d=c.a(),e=[];Aa(a,b);return Va(e.join(C(c).toString()),d)}function Ya(a){return Wa(Array.prototype.slice.call(arguments))}var Ua={};function Va(a,b){return E(a,b)}function E(a,b){var c=new B;c.b=a;c.c=b;return c}E("<!DOCTYPE html>",0);var Xa=E("",0),Za=E("<br>",0);var $a=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=C(Xa);return!b.parentElement});function ab(a,b){if($a())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=C(b)};function bb(a){return a=Ha(a,void 0)};var cb={},db={};function F(){throw Error("Do not instantiate directly");}F.prototype.C=null;F.prototype.b=function(){return this.a};F.prototype.toString=function(){return this.a};F.prototype.c=function(){if(this.D!==db)throw Error("Sanitized content was not of kind URI.");return new z(this.toString())};function eb(){F.call(this)}y(eb,F);eb.prototype.D=cb;function fb(a){fb[" "](a);return a}fb[" "]=ra;function gb(a,b){var c=hb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ib=-1!=A.indexOf("Opera"),H=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),jb=-1!=A.indexOf("Edge"),I=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),J=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),kb=-1!=A.indexOf("Macintosh");function lb(){var a=u.document;return a?a.documentMode:void 0}var mb;
a:{var nb="",ob=function(){var a=A;if(I)return/rv:([^\);]+)(\)|;)/.exec(a);if(jb)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(J)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ob&&(nb=ob?ob[1]:"");if(H){var pb=lb();if(null!=pb&&pb>parseFloat(nb)){mb=String(pb);break a}}mb=nb}var qb=mb,hb={};
function K(a){return gb(a,function(){for(var b=0,c=Ga(String(qb)).split("."),d=Ga(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",h=d[f]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==h[0].length)break;b=Pa(0==k[1].length?0:parseInt(k[1],10),0==h[1].length?0:parseInt(h[1],10))||Pa(0==k[2].length,0==h[2].length)||Pa(k[2],h[2]);k=k[3];h=h[3]}while(0==b)}return 0<=b})}var rb;
if(u.document&&H){var sb=lb();rb=sb?sb:parseInt(qb,10)||void 0}else rb=void 0;var L=rb;function tb(a){if(null!=a)switch(a.C){case 1:return 1;case -1:return-1;case 0:return 0}return null}var ub=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.C=d);return c}}(eb);/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var vb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(vb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function M(a){var b=HTMLElement.call(this)||this;a&&wb(a);return b}pa(M,HTMLElement);M.prototype.u=function(){console.warn(this.tagName,"has not implemented update")};M.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
M.prototype.s=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function wb(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var N=new Map;function O(a){var b=M.call(this)||this;a&&wb(a);return b}pa(O,M);O.prototype.connectedCallback=function(){var a=this.constructor,b=N.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):N.set(a,this)};O.prototype.disconnectedCallback=function(){var a=this.constructor;N.get(a)===this&&N.delete(a)};O.prototype.disconnectedCallback=O.prototype.disconnectedCallback;O.prototype.connectedCallback=O.prototype.connectedCallback;function P(){this.l=this.l;this.b=this.b}g=P.prototype;g.l=!1;g.P=function(){return this.l};g.ma=P.prototype.P;g.H=function(){this.l||(this.l=!0,this.o())};g.tb=function(a){a=wa(xb,a);this.l?a():(this.b||(this.b=[]),this.b.push(a))};g.o=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function xb(a){a&&"function"==typeof a.H&&a.H()};function Q(a,b){this.type=a;this.b=this.target=b;this.defaultPrevented=this.g=!1}Q.prototype.h=function(){this.g=!0};Q.prototype.c=function(){this.defaultPrevented=!0};var yb=!H||9<=Number(L),zb=!H||9<=Number(L),Ab=H&&!K("9"),Bb=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",ra,b),u.removeEventListener("test",ra,b)}catch(c){}return a}();var Cb;Cb=J?"webkitTransitionEnd":ib?"otransitionend":"transitionend";function R(a,b){Q.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.A=this.u=0;this.key="";this.j=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.R=null;this.T=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(I){a:{try{fb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.u=J||void 0!==a.offsetX?a.offsetX:a.layerX,this.A=J||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.T=kb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Db[a.pointerType]||"";this.R=a.state;this.a=a;a.defaultPrevented&&this.c()}}y(R,Q);var Eb=[1,4,2],Db={2:"touch",3:"pen",4:"mouse"};
R.prototype.Gb=function(){return(yb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Eb[0]))&&!(J&&kb&&this.ctrlKey)};R.prototype.h=function(){R.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};R.prototype.c=function(){R.w.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};R.prototype.Eb=function(){return this.a};var S="closure_listenable_"+(1E6*Math.random()|0),Fb=0;function Gb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Fb;this.v=this.B=!1}function Hb(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Ib(a){this.src=a;this.a={};this.b=0}Ib.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Ib.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var k=Jb(a,b,d,e);-1<k?(b=a[k],c||(b.B=!1)):(b=new Gb(b,this.src,f,!!d,e),b.B=c,a.push(b));return b};function Kb(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=za(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(Hb(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}
function Lb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Jb(a,c,d,e));return-1<b?a[b]:null}function Jb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Mb="closure_lm_"+(1E6*Math.random()|0),Nb={},Ob=0;function Pb(a,b,c,d,e){if(d&&d.once)return Qb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Pb(a,b[f],c,d,e);return null}c=Rb(c);return a&&a[S]?a.m(b,c,w(d)?!!d.capture:!!d,e):Sb(a,b,c,!1,d,e)}
function Sb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=w(e)?!!e.capture:!!e,h=Tb(a);h||(a[Mb]=h=new Ib(a));c=h.add(b,c,d,k,f);if(c.a)return c;d=Ub();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Bb||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Vb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ob++;return c}
function Ub(){var a=Wb,b=zb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Qb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Qb(a,b[f],c,d,e);return null}c=Rb(c);return a&&a[S]?a.g.add(String(b),c,!0,w(d)?!!d.capture:!!d,e):Sb(a,b,c,!0,d,e)}
function Xb(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[S])Kb(b.g,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Vb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ob--;(c=Tb(b))?(Kb(c,a),0==c.b&&(c.src=null,b[Mb]=null)):Hb(a)}}}function Vb(a){return a in Nb?Nb[a]:Nb[a]="on"+a}
function Yb(a,b,c,d){var e=!0;if(a=Tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.v&&(f=Zb(f,d),e=e&&!1!==f)}return e}function Zb(a,b){var c=a.listener,d=a.b||a.src;a.B&&Xb(a);return c.call(d,b)}
function Wb(a,b){if(a.v)return!0;if(!zb){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new R(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.g&&0<=e;e--){b.b=d[e];var f=Yb(d[e],a,!0,b);c=c&&f}for(e=0;!b.g&&e<d.length;e++)b.b=d[e],f=Yb(d[e],a,!1,b),c=
c&&f}return c}return Zb(a,new R(b,this))}function Tb(a){a=a[Mb];return a instanceof Ib?a:null}var $b="__closure_events_fn_"+(1E9*Math.random()>>>0);function Rb(a){if(v(a))return a;a[$b]||(a[$b]=function(b){return a.handleEvent(b)});return a[$b]};var ac=!H||9<=Number(L),bc=!I&&!H||H&&9<=Number(L)||I&&K("1.9.1"),cc=H&&!K("9"),dc=H||ib||J;function T(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}g=T.prototype;g.$a=function(){return new T(this.x,this.a)};g.aa=function(a){return a instanceof T&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.bb=function(a,b){a instanceof T?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};g.ab=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};g.wb=function(a,b){a=a*Math.PI/180;b=b||new T(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function U(a,b){this.width=a;this.height=b}g=U.prototype;g.cb=function(){return new U(this.width,this.height)};g.ya=function(){return Math.max(this.width,this.height)};g.La=function(){return Math.min(this.width,this.height)};g.sb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.ib=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ea=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ec(a,b){a.width*=b;a.height*=b;return a}g.yb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return ec(this,a)};
g.zb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return ec(this,a)};function fc(a){return a?new V(W(a)):ya||(ya=new V)}function gc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=hc(document,"*",a,b);return d||null}
function ic(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,k;k=b[f];f++)e==k.nodeName&&(a[d++]=k);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;k=b[f];f++){e=k.className;var h;if(h="function"==typeof e.split)h=0<=za(e.split(/\s+/),c);h&&(a[d++]=k)}a.length=d;return a}return b}
function hc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):ic(a,b,c,d)[0]||null}function jc(a,b){Da(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.F());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:kc.hasOwnProperty(d)?a.setAttribute(kc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var kc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function lc(a){a=a.document;a=mc(a)?a.documentElement:a.body;return new U(a.clientWidth,a.clientHeight)}function nc(a){return a.scrollingElement?a.scrollingElement:!J&&mc(a)?a.documentElement:a.body||a.documentElement}
function oc(a){return a.parentWindow||a.defaultView}function pc(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];ta(f)&&!qc(f)?Aa(rc(f)?Ca(f):f,e):e(f)}}function X(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function mc(a){return"CSS1Compat"==a.compatMode}function sc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Y(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function tc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function qc(a){return w(a)&&0<a.nodeType}function uc(a){return w(a)&&1==a.nodeType}function vc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function wc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return xc(b,a)}function xc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function W(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function yc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else sc(a),a.appendChild(W(a).createTextNode(String(b)))}function zc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||zc(a,b,c,d))return!0;a=a.nextSibling}return!1}var Ac={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Bc={IMG:" ",BR:"\n"};
function Cc(a){return Dc(a)&&Ec(a)}function Dc(a){return H&&!K("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Ec(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Fc(a){if(cc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Gc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");cc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Gc(a,b,c){if(!(a.nodeName in Ac))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Bc)b.push(Bc[a.nodeName]);else for(a=a.firstChild;a;)Gc(a,b,c),a=a.nextSibling}function rc(a){if(a&&"number"==typeof a.length){if(w(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return!1}
function Hc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Ic(a,function(f){var k;(k=!e||f.nodeName==e)&&!(k=!c)&&(k="string"===typeof f.className)&&(k=0<=za(f.className.split(/\s+/),c));return k},!0,d)}function Ic(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function V(a){this.a=a||u.document||document}g=V.prototype;g.qa=fc;g.Ab=function(a){this.a=a};g.na=function(){return this.a};
g.N=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ja=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.V=V.prototype.N;g.Va=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.O=function(a,b,c){return ic(this.a,a,b,c)};g.sa=function(a,b,c){return hc(this.a,a,b,c)};g.ta=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):ic(document,"*",a,b)};g.ra=function(a,b){return gc(a,b||this.a)};
g.Ka=function(a,b){return gc(a,b||this.a)};g.W=V.prototype.O;g.Cb=jc;g.Na=function(a){return lc(a||oc(this.a)||window)};g.oa=function(){var a=oc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=lc(a).height,mc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.M=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),k=e[1];if(!ac&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',bb(k.name),'"');if(k.type){f.push(' type="',bb(k.type),'"');var h={};Fa(h,k);delete h.type;k=h}f.push(">");f=f.join("")}f=X(d,f);k&&("string"===typeof k?f.className=k:Array.isArray(k)?f.className=k.join(" "):jc(f,k));2<e.length&&pc(d,f,e,2);return f};g.X=V.prototype.M;g.Ua=function(a){return this.a.createTextNode(String(a))};
g.$=function(a,b,c){var d=this.a;c=!!c;for(var e=X(d,"TABLE"),f=e.appendChild(X(d,"TBODY")),k=0;k<a;k++){for(var h=X(d,"TR"),l=0;l<b;l++){var m=X(d,"TD");c&&yc(m,"\u00a0");h.appendChild(m)}f.appendChild(h)}return e};g.xb=function(a){var b=this.a;var c=X(b,"DIV");H?(a=Ya(Za,a),ab(c,a),c.removeChild(c.firstChild)):ab(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.pa=function(){return nc(this.a)};
g.ga=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Ra=function(a,b){a.appendChild(b)};g.Qa=function(a,b){pc(W(a),a,arguments,1)};g.Sa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.vb=sc;g.gb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.eb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Wa=Y;g.Xa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.fa=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Y(a)}};
g.la=function(a){return bc&&void 0!=a.children?a.children:Ba(a.childNodes,function(b){return 1==b.nodeType})};g.ua=function(a){return void 0!==a.firstElementChild?a.firstElementChild:tc(a.firstChild,!0)};g.xa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:tc(a.lastChild,!1)};g.za=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:tc(a.nextSibling,!0)};g.Ha=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:tc(a.previousSibling,!1)};
g.Aa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ia=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.lb=qc;g.hb=uc;g.nb=function(a){return w(a)&&a.window==a};g.Ga=function(a){var b;if(dc&&!(H&&K("9")&&!K("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return uc(b)?b:null};
g.Ta=vc;
g.Z=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(H&&!(9<=Number(L))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?xc(a,b):!c&&vc(e,b)?-1*wc(a,b):!d&&vc(f,a)?wc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=W(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};g.ba=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],k=arguments[b];k;)f.unshift(k),k=k.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){k=d[0][b];for(var h=1;h<c;h++)if(k!=d[h][b])return f;f=k}return f};g.Fa=W;g.va=function(a){return a.contentDocument||a.contentWindow.document};
g.wa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?oc(c):window}else d=null;b=d}return b}catch(e){}return null};g.Db=yc;g.Ea=function(a){if("outerHTML"in a)return a.outerHTML;var b=X(W(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ca=function(a,b){var c=[];return zc(a,b,c,!0)?c[0]:void 0};g.da=function(a,b){var c=[];zc(a,b,c,!1);return c};g.kb=Cc;g.Bb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.jb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Dc(a)||Ec(a)):Cc(a))&&H){var c;!v(a.getBoundingClientRect)||H&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ma=Fc;g.Ca=function(a){return Fc(a).length};
g.Da=function(a,b){b=b||W(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Fc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ba=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Ac))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Bc)d+=Bc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);w(c)&&(c.ub=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.mb=rc;g.ja=Hc;g.ia=function(a,b,c){return Hc(a,null,b,c)};g.ha=Ic;g.ka=function(a){return a.getContext("2d")};function Jc(a,b){if(!v(a))if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};function Kc(a,b,c){P.call(this);this.A=null!=c?x(a,c):a;this.u=b;this.s=x(this.S,this);this.c=!1;this.g=0;this.h=this.a=null;this.j=[]}y(Kc,P);g=Kc.prototype;g.I=function(a){this.j=arguments;this.c=!1;this.a?this.h=xa()+this.u:this.a=Jc(this.s,this.u)};g.Oa=function(){++this.g};g.Pa=function(){this.g&&(--this.g,!this.g&&this.c&&(this.c=!1,this.A.apply(null,this.j)))};g.o=function(){this.a&&(u.clearTimeout(this.a),this.a=null);this.h=null;this.c=!1;this.j=[];Kc.w.o.call(this)};
g.S=function(){this.h?(this.a=Jc(this.s,this.h-xa()),this.h=null):(this.a=null,this.g?this.c=!0:(this.c=!1,this.A.apply(null,this.j)))};function Lc(a){P.call(this);this.c=a;this.a={}}y(Lc,P);var Mc=[];g=Lc.prototype;g.m=function(a,b,c,d){return Nc(this,a,b,c,d)};g.pb=function(a,b,c,d,e){return Nc(this,a,b,c,d,e)};function Nc(a,b,c,d,e,f){Array.isArray(c)||(c&&(Mc[0]=c.toString()),c=Mc);for(var k=0;k<c.length;k++){var h=Pb(b,c[k],d||a.handleEvent,e||!1,f||a.c||a);if(!h)break;a.a[h.key]=h}return a}g.Za=function(a,b,c,d){return Oc(this,a,b,c,d)};g.ob=function(a,b,c,d,e){return Oc(this,a,b,c,d,e)};
function Oc(a,b,c,d,e,f){if(Array.isArray(c))for(var k=0;k<c.length;k++)Oc(a,b,c[k],d,e,f);else{b=Qb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.qb=function(a,b,c,d){b.m(a,c,d,this.c||this);return this};g.rb=function(a,b,c,d,e){b.m(a,c,d,e||this.c||this);return this};g.Ya=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.K=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.K(a,b[f],c,d,e);else c=c||this.handleEvent,d=w(d)?!!d.capture:!!d,e=e||this.c||this,c=Rb(c),d=!!d,b=a&&a[S]?Lb(a.g,String(b),c,d,e):a?(a=Tb(a))?Lb(a,b,c,d,e):null:null,b&&(Xb(b),delete this.a[b.key])};g.Fb=function(a,b,c,d,e){b.K(a,c,d,e||this.c||this,this);return this};function Pc(a){Da(a.a,function(b,c){this.a.hasOwnProperty(c)&&Xb(b)},a);a.a={}}g.o=function(){Lc.w.o.call(this);Pc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Qc(a){a=(a||Rc).U;a=null!=a&&a.D===cb?a:a instanceof B?ub(C(a).toString(),a.a()):ub(bb(String(String(a))),tb(a));var b=ub('<span class="devsite-tooltip-msg">'+a+"</span>");a=fc();a=X(a.a,"DIV");if(w(b))if(b instanceof F){if(b.D!==cb)throw Error("Sanitized content was not of kind HTML.");b=E(b.toString(),b.C||null)}else b=D("zSoyz");else b=D(String(b));ab(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Rc={};function Sc(a){try{var b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}H&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Tc(a){var b=W(a),c=new T(0,0);var d=b?W(b):document;d=!H||9<=Number(L)||mc(fc(d).a)?d.documentElement:d.body;if(a==d)return c;a=Sc(a);d=fc(b).a;b=nc(d);d=oc(d);b=H&&K("10")&&d.pageYOffset!=b.scrollTop?new T(b.scrollLeft,b.scrollTop):new T(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop);c.x=a.left+b.x;c.a=a.top+b.a;return c}
function Uc(a){var b=Vc;a:{var c=W(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}c||(c=a.currentStyle?a.currentStyle.display:null);if("none"!=(c||a.style&&a.style.display))return b(a);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}
function Vc(a){var b=a.offsetWidth,c=a.offsetHeight,d=J&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Sc(a),new U(a.right-a.left,a.bottom-a.top)):new U(b,c)};var Wc=["dl.google.com"],Xc="abc.xyz admob.com android.com blogger.com blogspot.com chrome.com chromium.org domains.google doubleclick.com feedburner.com g.co ggpht.com gmail.com gmodules.com goo.gl google.com google.org googleapis.com googleapps.com googlecode.com googledrive.com googlemail.com googlesource.com googlesyndication.com googletagmanager.com googleusercontent.com gv.com keyhole.com madewithcode.com panoramio.com urchin.com withgoogle.com youtu.be youtube.com ytimg.com".split(" ");
function Z(){var a=O.call(this)||this;a.b=new Lc;a.a=null;a.c=null;a.h=new Kc(function(){return Yc(a)},250);return a}pa(Z,O);Z.prototype.connectedCallback=function(){document.body.hasAttribute("touch")?Y(this):(Zc(this),this.h.I())};Z.prototype.disconnectedCallback=function(){O.prototype.disconnectedCallback.call(this);Pc(this.b)};
function Zc(a){a.b.m(document.body,"devsite-content-updated",function(){return a.h.I()});a.b.m(document.body,"onpointermove"in window?"pointermove":"mousemove",function(b){b=b.target;for(var c=!1;b;){b.hasAttribute&&(c=b.hasAttribute("tooltip")&&b.clientWidth<b.scrollWidth||b.hasAttribute("data-title")||b.hasAttribute("data-tooltip"));if(c)break;b=b.parentNode}b&&!b.hasAttribute("no-tooltip")?$c(a,b):ad(a)});a.b.m(document.body,["devsite-sticky-scroll","devsite-sticky-resize"],function(){return ad(a)})}
function $c(a,b){if(a.a!==b){ad(a);var c=b.getAttribute("data-tooltip")||b.getAttribute("data-title")||b.textContent.trim(),d=Qc({U:c});d.style.opacity=0;document.body.appendChild(d);var e=lc(window),f=Uc(b),k=Uc(d),h=Tc(b);c=h.a+f.height;f=h.x+f.width/2-k.width/2;k.width>e.width?f=0:(f=Math.max(f,8),e=e.width-(f+k.width+8),0>e&&(f=f+e-8));d.style.top=c+"px";d.style.left=f+"px";a.a=b;a.c=d;window.requestAnimationFrame(function(){d.style.opacity=1})}}
function ad(a){if(a.a){a.a=null;var b=a.c;a.c=null;Qb(b,Cb,function(){Y(b);sc(b)});window.setTimeout(function(){Y(b);sc(b)},1E3);b.style.opacity=0}}
function Yc(a){Array.from(document.querySelectorAll(".devsite-article-body [title]")).forEach(function(b){b.setAttribute("data-title",b.getAttribute("title"));b.removeAttribute("title")});a.hasAttribute("blocked-link")&&Array.from(document.getElementsByTagName("a")).forEach(function(b){if(b.hasAttribute("href")){for(var c=(new URL(b.getAttribute("href"),document.location.origin)).hostname.replace("www.",""),d=0;d<Wc.length;d++)if(-1!==c.indexOf(Wc[d]))return;for(d=0;d<Xc.length;d++)if(-1!==c.indexOf(Xc[d])){b.setAttribute("data-title",
"This link may not be accessible in your region.");b.removeAttribute("title");break}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tooltip",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTooltip",a)};}).call(this);
