(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function g(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var h=g(this),k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={s:!0},p={};try{p.__proto__=n;m=p.s;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=l;
function u(a,b){a.prototype=k(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.A=b.prototype}function v(a,b){if(b){var c=h;a=a.split(".");for(var e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&f(c,a,{configurable:!0,writable:!0,value:b})}}
v("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var e=this.length,d=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var q=0;q<d&&c<e;)if(this[c++]!=b[q++])return!1;return q>=d}});v("Object.setPrototypeOf",function(a){return a||t});
var w=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,e,d){c=b(c,e);d&&Reflect.setPrototypeOf(c,d.prototype);return c}}return function(c,e,d){void 0===d&&(d=c);d=k(d.prototype||Object.prototype);return Function.prototype.apply.call(c,d,e)||d}}();v("Reflect.construct",function(){return w});
function x(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.B=function(e,d,q){for(var D=Array(arguments.length-2),r=2;r<arguments.length;r++)D[r-2]=arguments[r];return b.prototype[d].apply(e,D)}};function y(a,b){if(b)a=a.replace(z,"&amp;").replace(A,"&lt;").replace(B,"&gt;").replace(C,"&quot;").replace(E,"&#39;").replace(F,"&#0;");else{if(!G.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(z,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(A,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(B,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(C,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(E,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(F,"&#0;"))}return a}var z=/&/g,A=/</g,B=/>/g,C=/"/g,E=/'/g,F=/\x00/g,G=/[\x00&<>"']/;function H(a){this.b=I===I&&a||"";this.f=J}H.prototype.g=!0;H.prototype.a=function(){return this.b.toString()};H.prototype.l=!0;H.prototype.j=function(){return 1};var J={},I={};function K(){this.w="";this.o=L}K.prototype.g=!0;var L={};K.prototype.a=function(){return""};function M(){this.v="";this.m=N}M.prototype.g=!0;var N={};M.prototype.a=function(){return""};function O(){this.b="";this.u=P;this.f=null}O.prototype.l=!0;O.prototype.j=function(){return this.f};O.prototype.g=!0;O.prototype.a=function(){return this.b.toString()};function Q(a){return a instanceof O&&a.constructor===O&&a.u===P?a.b:"type_error:SafeHtml"}function R(a){if(a instanceof O)return a;var b="object"==typeof a,c=null;b&&a.l&&(c=a.j());a=y(b&&a.g?a.a():String(a));return S(a,c)}var P={};function S(a,b){var c=new O;c.b=a;c.f=b;return c}S("<!DOCTYPE html>",0);var aa=S("",0);S("<br>",0);var ba=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=Q(aa);return!b.parentElement});var T={},ca={},da={};function U(){throw Error("Do not instantiate directly");}U.prototype.i=null;U.prototype.toString=function(){return this.h};U.prototype.a=function(){if(this.c!==ca)throw Error("Sanitized content was not of kind URI.");return new H(this.toString())};function V(){U.call(this)}x(V,U);V.prototype.c=T;var ea=function(a){function b(c){this.h=c}b.prototype=a.prototype;return function(c,e){c=new b(String(c));void 0!==e&&(c.i=e);return c}}(V);function W(a){return a.replace(/<\//g,"<\\/").replace(/\]\]>/g,"]]\\>")}function X(a){null!=a&&a.c===T?a=String(String(a.h).replace(fa,"").replace(ha,"&lt;")).replace(ia,ja):(a=String(a),a=y(a,void 0));return a}
var ka={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function ja(a){return ka[a]}
var ia=/[\x00\x22\x27\x3c\x3e]/g,la=/^(?!-*(?:expression|(?:moz-)?binding))(?:(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|(?:rgb|hsl)a?\([0-9.%,\u0020]+\)|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,4}|%)?|!important)(?:\s*[,\u0020]\s*|$))*$/i,fa=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,ha=/</g;/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var ma=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(ma&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Y(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}u(Y,HTMLElement);Y.prototype.f=function(){console.warn(this.tagName,"has not implemented update")};Y.prototype.a=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Y.prototype.b=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Z(){return Y.apply(this,arguments)||this}u(Z,Y);
Z.prototype.connectedCallback=function(){var a;if(this.hasAttribute("single-color")){var b=this.getAttribute("single-color");b&&b.startsWith("#")&&(a=b)}var c="";for(b=0;4>b;b++){var e='<div class="devsite-spinner__layer devsite-spinner__layer-'+X(1+b)+'"';if(a){if(null!=a&&a.c===da)var d=W(a.h);else null==a?d="":a instanceof K?d=W(a instanceof K&&a.constructor===K&&a.o===L?a.w:"type_error:SafeStyle"):a instanceof M?d=W(a instanceof M&&a.constructor===M&&a.m===N?a.v:"type_error:SafeStyleSheet"):(d=
String(a),d=la.test(d)?d:"zSoyz");d=' style="border-color: '+X(d)+';"'}else d="";c+=e+d+'><div class="devsite-spinner__circle-clipper devsite-spinner__left"><div class="devsite-spinner__circle"></div></div><div class="devsite-spinner__gap-patch"><div class="devsite-spinner__circle"></div></div><div class="devsite-spinner__circle-clipper devsite-spinner__right"><div class="devsite-spinner__circle"></div></div></div>'}a=ea(c);b=typeof a;if("object"==b&&null!=a||"function"==b)if(a instanceof U){if(a.c!==
T)throw Error("Sanitized content was not of kind HTML.");a=S(a.toString(),a.i||null)}else a=R("zSoyz");else a=R(String(a));if(ba())for(;this.lastChild;)this.removeChild(this.lastChild);this.innerHTML=Q(a);if(a=this.getAttribute("size"))this.style.width=a+"px",this.style.height=a+"px"};Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-spinner",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteSpinner",a)};}).call(this);
